// Generated by `cargo dotnet add-nuget` — do not hand-edit (re-run add-nuget instead).
#[allow(unused_imports)]
use mycorrhiza::bindings::System;

pub trait UpcastTo<T> { fn upcast(self) -> T; }
pub mod Microsoft{
pub mod Data{
pub mod Sqlite{
pub type SqliteBlob =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"Microsoft.Data.Sqlite","Microsoft.Data.Sqlite.SqliteBlob">;
use super::super::super::*;
impl UpcastTo<System::IO::Stream> for SqliteBlob {
 fn upcast(self)->System::IO::Stream{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::IO::Stream,SqliteBlob>(self)
}} 
pub trait SqliteBlob_Methods {
    fn get_can_read(self) -> bool;
    fn get_can_write(self) -> bool;
    fn get_can_seek(self) -> bool;
    fn get_length(self) -> i64;
    fn get_position(self) -> i64;
    fn set_position(self, a1: i64);
    fn flush(self);
    fn set_length(self, a1: i64);
}
impl SqliteBlob_Methods for SqliteBlob {
    fn get_can_read(self) -> bool { self.virt0::<"get_CanRead", bool>() }
    fn get_can_write(self) -> bool { self.virt0::<"get_CanWrite", bool>() }
    fn get_can_seek(self) -> bool { self.virt0::<"get_CanSeek", bool>() }
    fn get_length(self) -> i64 { self.virt0::<"get_Length", i64>() }
    fn get_position(self) -> i64 { self.virt0::<"get_Position", i64>() }
    fn set_position(self, a1: i64) { self.instance1::<"set_Position", i64, ()>(a1) }
    fn flush(self) { self.virt0::<"Flush", ()>() }
    fn set_length(self, a1: i64) { self.instance1::<"SetLength", i64, ()>(a1) }
}
pub type SqliteCommand =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"Microsoft.Data.Sqlite","Microsoft.Data.Sqlite.SqliteCommand">;
use super::super::super::*;
pub trait SqliteCommand_Methods {
    fn get_command_text(self) -> System::String;
    fn set_command_text(self, a1: System::String);
    fn get_connection(self) -> Microsoft::Data::Sqlite::SqliteConnection;
    fn set_connection(self, a1: Microsoft::Data::Sqlite::SqliteConnection);
    fn get_transaction(self) -> Microsoft::Data::Sqlite::SqliteTransaction;
    fn set_transaction(self, a1: Microsoft::Data::Sqlite::SqliteTransaction);
    fn get_parameters(self) -> Microsoft::Data::Sqlite::SqliteParameterCollection;
    fn get_command_timeout(self) -> i32;
    fn set_command_timeout(self, a1: i32);
    fn get_design_time_visible(self) -> bool;
    fn set_design_time_visible(self, a1: bool);
    fn create_parameter(self) -> Microsoft::Data::Sqlite::SqliteParameter;
    fn prepare(self);
    fn execute_reader(self) -> Microsoft::Data::Sqlite::SqliteDataReader;
    fn execute_non_query(self) -> i32;
    fn execute_scalar(self) -> System::Object;
    fn cancel(self);
    fn new() -> Self;
}
impl SqliteCommand_Methods for SqliteCommand {
    fn get_command_text(self) -> System::String { self.virt0::<"get_CommandText", System::String>() }
    fn set_command_text(self, a1: System::String) { self.instance1::<"set_CommandText", System::String, ()>(a1) }
    fn get_connection(self) -> Microsoft::Data::Sqlite::SqliteConnection { self.virt0::<"get_Connection", Microsoft::Data::Sqlite::SqliteConnection>() }
    fn set_connection(self, a1: Microsoft::Data::Sqlite::SqliteConnection) { self.instance1::<"set_Connection", Microsoft::Data::Sqlite::SqliteConnection, ()>(a1) }
    fn get_transaction(self) -> Microsoft::Data::Sqlite::SqliteTransaction { self.virt0::<"get_Transaction", Microsoft::Data::Sqlite::SqliteTransaction>() }
    fn set_transaction(self, a1: Microsoft::Data::Sqlite::SqliteTransaction) { self.instance1::<"set_Transaction", Microsoft::Data::Sqlite::SqliteTransaction, ()>(a1) }
    fn get_parameters(self) -> Microsoft::Data::Sqlite::SqliteParameterCollection { self.virt0::<"get_Parameters", Microsoft::Data::Sqlite::SqliteParameterCollection>() }
    fn get_command_timeout(self) -> i32 { self.virt0::<"get_CommandTimeout", i32>() }
    fn set_command_timeout(self, a1: i32) { self.instance1::<"set_CommandTimeout", i32, ()>(a1) }
    fn get_design_time_visible(self) -> bool { self.virt0::<"get_DesignTimeVisible", bool>() }
    fn set_design_time_visible(self, a1: bool) { self.instance1::<"set_DesignTimeVisible", bool, ()>(a1) }
    fn create_parameter(self) -> Microsoft::Data::Sqlite::SqliteParameter { self.virt0::<"CreateParameter", Microsoft::Data::Sqlite::SqliteParameter>() }
    fn prepare(self) { self.virt0::<"Prepare", ()>() }
    fn execute_reader(self) -> Microsoft::Data::Sqlite::SqliteDataReader { self.virt0::<"ExecuteReader", Microsoft::Data::Sqlite::SqliteDataReader>() }
    fn execute_non_query(self) -> i32 { self.virt0::<"ExecuteNonQuery", i32>() }
    fn execute_scalar(self) -> System::Object { self.virt0::<"ExecuteScalar", System::Object>() }
    fn cancel(self) { self.virt0::<"Cancel", ()>() }
    fn new() -> Self { Self::ctor0() }
}
pub type SqliteConnection =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"Microsoft.Data.Sqlite","Microsoft.Data.Sqlite.SqliteConnection">;
use super::super::super::*;
pub trait SqliteConnection_Methods {
    fn get_connection_string(self) -> System::String;
    fn set_connection_string(self, a1: System::String);
    fn get_database(self) -> System::String;
    fn get_data_source(self) -> System::String;
    fn get_default_timeout(self) -> i32;
    fn set_default_timeout(self, a1: i32);
    fn get_server_version(self) -> System::String;
    fn clear_all_pools();
    fn clear_pool(a1: Microsoft::Data::Sqlite::SqliteConnection);
    fn open(self);
    fn close(self);
    fn create_command(self) -> Microsoft::Data::Sqlite::SqliteCommand;
    fn begin_transaction(self) -> Microsoft::Data::Sqlite::SqliteTransaction;
    fn change_database(self, a1: System::String);
    fn enable_extensions(self, a1: bool);
    fn load_extension(self, a1: System::String, a2: System::String);
    fn backup_database(self, a1: Microsoft::Data::Sqlite::SqliteConnection);
    fn new() -> Self;
}
impl SqliteConnection_Methods for SqliteConnection {
    fn get_connection_string(self) -> System::String { self.virt0::<"get_ConnectionString", System::String>() }
    fn set_connection_string(self, a1: System::String) { self.instance1::<"set_ConnectionString", System::String, ()>(a1) }
    fn get_database(self) -> System::String { self.virt0::<"get_Database", System::String>() }
    fn get_data_source(self) -> System::String { self.virt0::<"get_DataSource", System::String>() }
    fn get_default_timeout(self) -> i32 { self.virt0::<"get_DefaultTimeout", i32>() }
    fn set_default_timeout(self, a1: i32) { self.instance1::<"set_DefaultTimeout", i32, ()>(a1) }
    fn get_server_version(self) -> System::String { self.virt0::<"get_ServerVersion", System::String>() }
    fn clear_all_pools() { Self::static0::<"ClearAllPools", ()>() }
    fn clear_pool(a1: Microsoft::Data::Sqlite::SqliteConnection) { Self::static1::<"ClearPool", Microsoft::Data::Sqlite::SqliteConnection, ()>(a1) }
    fn open(self) { self.virt0::<"Open", ()>() }
    fn close(self) { self.virt0::<"Close", ()>() }
    fn create_command(self) -> Microsoft::Data::Sqlite::SqliteCommand { self.virt0::<"CreateCommand", Microsoft::Data::Sqlite::SqliteCommand>() }
    fn begin_transaction(self) -> Microsoft::Data::Sqlite::SqliteTransaction { self.virt0::<"BeginTransaction", Microsoft::Data::Sqlite::SqliteTransaction>() }
    fn change_database(self, a1: System::String) { self.instance1::<"ChangeDatabase", System::String, ()>(a1) }
    fn enable_extensions(self, a1: bool) { self.instance1::<"EnableExtensions", bool, ()>(a1) }
    fn load_extension(self, a1: System::String, a2: System::String) { self.instance2::<"LoadExtension", System::String, System::String, ()>(a1, a2) }
    fn backup_database(self, a1: Microsoft::Data::Sqlite::SqliteConnection) { self.instance1::<"BackupDatabase", Microsoft::Data::Sqlite::SqliteConnection, ()>(a1) }
    fn new() -> Self { Self::ctor0() }
}
pub type SqliteConnectionStringBuilder =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"Microsoft.Data.Sqlite","Microsoft.Data.Sqlite.SqliteConnectionStringBuilder">;
use super::super::super::*;
pub trait SqliteConnectionStringBuilder_Methods {
    fn get_data_source(self) -> System::String;
    fn set_data_source(self, a1: System::String);
    fn get_keys(self) -> System::Collections::ICollection;
    fn get_values(self) -> System::Collections::ICollection;
    fn get_password(self) -> System::String;
    fn set_password(self, a1: System::String);
    fn get_recursive_triggers(self) -> bool;
    fn set_recursive_triggers(self, a1: bool);
    fn get_default_timeout(self) -> i32;
    fn set_default_timeout(self, a1: i32);
    fn get_pooling(self) -> bool;
    fn set_pooling(self, a1: bool);
    fn get_item(self, a1: System::String) -> System::Object;
    fn set_item(self, a1: System::String, a2: System::Object);
    fn clear(self);
    fn contains_key(self, a1: System::String) -> bool;
    fn remove(self, a1: System::String) -> bool;
    fn should_serialize(self, a1: System::String) -> bool;
    fn new() -> Self;
}
impl SqliteConnectionStringBuilder_Methods for SqliteConnectionStringBuilder {
    fn get_data_source(self) -> System::String { self.virt0::<"get_DataSource", System::String>() }
    fn set_data_source(self, a1: System::String) { self.instance1::<"set_DataSource", System::String, ()>(a1) }
    fn get_keys(self) -> System::Collections::ICollection { self.virt0::<"get_Keys", System::Collections::ICollection>() }
    fn get_values(self) -> System::Collections::ICollection { self.virt0::<"get_Values", System::Collections::ICollection>() }
    fn get_password(self) -> System::String { self.instance0::<"get_Password", System::String>() }
    fn set_password(self, a1: System::String) { self.instance1::<"set_Password", System::String, ()>(a1) }
    fn get_recursive_triggers(self) -> bool { self.instance0::<"get_RecursiveTriggers", bool>() }
    fn set_recursive_triggers(self, a1: bool) { self.instance1::<"set_RecursiveTriggers", bool, ()>(a1) }
    fn get_default_timeout(self) -> i32 { self.instance0::<"get_DefaultTimeout", i32>() }
    fn set_default_timeout(self, a1: i32) { self.instance1::<"set_DefaultTimeout", i32, ()>(a1) }
    fn get_pooling(self) -> bool { self.instance0::<"get_Pooling", bool>() }
    fn set_pooling(self, a1: bool) { self.instance1::<"set_Pooling", bool, ()>(a1) }
    fn get_item(self, a1: System::String) -> System::Object { self.instance1::<"get_Item", System::String, System::Object>(a1) }
    fn set_item(self, a1: System::String, a2: System::Object) { self.instance2::<"set_Item", System::String, System::Object, ()>(a1, a2) }
    fn clear(self) { self.virt0::<"Clear", ()>() }
    fn contains_key(self, a1: System::String) -> bool { self.instance1::<"ContainsKey", System::String, bool>(a1) }
    fn remove(self, a1: System::String) -> bool { self.instance1::<"Remove", System::String, bool>(a1) }
    fn should_serialize(self, a1: System::String) -> bool { self.instance1::<"ShouldSerialize", System::String, bool>(a1) }
    fn new() -> Self { Self::ctor0() }
}
pub type SqliteDataReader =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"Microsoft.Data.Sqlite","Microsoft.Data.Sqlite.SqliteDataReader">;
use super::super::super::*;
pub trait SqliteDataReader_Methods {
    fn get_depth(self) -> i32;
    fn get_field_count(self) -> i32;
    fn get_has_rows(self) -> bool;
    fn get_is_closed(self) -> bool;
    fn get_records_affected(self) -> i32;
    fn get_item(self, a1: System::String) -> System::Object;
    fn get_enumerator(self) -> System::Collections::IEnumerator;
    fn read(self) -> bool;
    fn next_result(self) -> bool;
    fn close(self);
    fn get_name(self, a1: i32) -> System::String;
    fn get_ordinal(self, a1: System::String) -> i32;
    fn get_data_type_name(self, a1: i32) -> System::String;
    fn get_field_type(self, a1: i32) -> System::Type;
    fn is_dbnull(self, a1: i32) -> bool;
    fn get_boolean(self, a1: i32) -> bool;
    fn get_byte(self, a1: i32) -> u8;
    fn get_double(self, a1: i32) -> f64;
    fn get_float(self, a1: i32) -> f32;
    fn get_int16(self, a1: i32) -> i16;
    fn get_int32(self, a1: i32) -> i32;
    fn get_int64(self, a1: i32) -> i64;
    fn get_string(self, a1: i32) -> System::String;
    fn get_stream(self, a1: i32) -> System::IO::Stream;
    fn get_text_reader(self, a1: i32) -> System::IO::TextReader;
    fn get_value(self, a1: i32) -> System::Object;
}
impl SqliteDataReader_Methods for SqliteDataReader {
    fn get_depth(self) -> i32 { self.virt0::<"get_Depth", i32>() }
    fn get_field_count(self) -> i32 { self.virt0::<"get_FieldCount", i32>() }
    fn get_has_rows(self) -> bool { self.virt0::<"get_HasRows", bool>() }
    fn get_is_closed(self) -> bool { self.virt0::<"get_IsClosed", bool>() }
    fn get_records_affected(self) -> i32 { self.virt0::<"get_RecordsAffected", i32>() }
    fn get_item(self, a1: System::String) -> System::Object { self.instance1::<"get_Item", System::String, System::Object>(a1) }
    fn get_enumerator(self) -> System::Collections::IEnumerator { self.virt0::<"GetEnumerator", System::Collections::IEnumerator>() }
    fn read(self) -> bool { self.virt0::<"Read", bool>() }
    fn next_result(self) -> bool { self.virt0::<"NextResult", bool>() }
    fn close(self) { self.virt0::<"Close", ()>() }
    fn get_name(self, a1: i32) -> System::String { self.instance1::<"GetName", i32, System::String>(a1) }
    fn get_ordinal(self, a1: System::String) -> i32 { self.instance1::<"GetOrdinal", System::String, i32>(a1) }
    fn get_data_type_name(self, a1: i32) -> System::String { self.instance1::<"GetDataTypeName", i32, System::String>(a1) }
    fn get_field_type(self, a1: i32) -> System::Type { self.instance1::<"GetFieldType", i32, System::Type>(a1) }
    fn is_dbnull(self, a1: i32) -> bool { self.instance1::<"IsDBNull", i32, bool>(a1) }
    fn get_boolean(self, a1: i32) -> bool { self.instance1::<"GetBoolean", i32, bool>(a1) }
    fn get_byte(self, a1: i32) -> u8 { self.instance1::<"GetByte", i32, u8>(a1) }
    fn get_double(self, a1: i32) -> f64 { self.instance1::<"GetDouble", i32, f64>(a1) }
    fn get_float(self, a1: i32) -> f32 { self.instance1::<"GetFloat", i32, f32>(a1) }
    fn get_int16(self, a1: i32) -> i16 { self.instance1::<"GetInt16", i32, i16>(a1) }
    fn get_int32(self, a1: i32) -> i32 { self.instance1::<"GetInt32", i32, i32>(a1) }
    fn get_int64(self, a1: i32) -> i64 { self.instance1::<"GetInt64", i32, i64>(a1) }
    fn get_string(self, a1: i32) -> System::String { self.instance1::<"GetString", i32, System::String>(a1) }
    fn get_stream(self, a1: i32) -> System::IO::Stream { self.instance1::<"GetStream", i32, System::IO::Stream>(a1) }
    fn get_text_reader(self, a1: i32) -> System::IO::TextReader { self.instance1::<"GetTextReader", i32, System::IO::TextReader>(a1) }
    fn get_value(self, a1: i32) -> System::Object { self.instance1::<"GetValue", i32, System::Object>(a1) }
}
pub type SqliteException =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"Microsoft.Data.Sqlite","Microsoft.Data.Sqlite.SqliteException">;
use super::super::super::*;
pub trait SqliteException_Methods {
    fn get_sqlite_error_code(self) -> i32;
    fn get_sqlite_extended_error_code(self) -> i32;
    fn new(a1: System::String, a2: i32) -> Self;
}
impl SqliteException_Methods for SqliteException {
    fn get_sqlite_error_code(self) -> i32 { self.virt0::<"get_SqliteErrorCode", i32>() }
    fn get_sqlite_extended_error_code(self) -> i32 { self.virt0::<"get_SqliteExtendedErrorCode", i32>() }
    fn new(a1: System::String, a2: i32) -> Self { Self::ctor2(a1, a2) }
}
pub type SqliteFactory =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"Microsoft.Data.Sqlite","Microsoft.Data.Sqlite.SqliteFactory">;
use super::super::super::*;
pub type SqliteParameter =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"Microsoft.Data.Sqlite","Microsoft.Data.Sqlite.SqliteParameter">;
use super::super::super::*;
pub trait SqliteParameter_Methods {
    fn get_is_nullable(self) -> bool;
    fn set_is_nullable(self, a1: bool);
    fn get_parameter_name(self) -> System::String;
    fn set_parameter_name(self, a1: System::String);
    fn get_size(self) -> i32;
    fn set_size(self, a1: i32);
    fn get_source_column(self) -> System::String;
    fn set_source_column(self, a1: System::String);
    fn get_source_column_null_mapping(self) -> bool;
    fn set_source_column_null_mapping(self, a1: bool);
    fn get_value(self) -> System::Object;
    fn set_value(self, a1: System::Object);
    fn reset_db_type(self);
    fn reset_sqlite_type(self);
    fn new() -> Self;
}
impl SqliteParameter_Methods for SqliteParameter {
    fn get_is_nullable(self) -> bool { self.virt0::<"get_IsNullable", bool>() }
    fn set_is_nullable(self, a1: bool) { self.instance1::<"set_IsNullable", bool, ()>(a1) }
    fn get_parameter_name(self) -> System::String { self.virt0::<"get_ParameterName", System::String>() }
    fn set_parameter_name(self, a1: System::String) { self.instance1::<"set_ParameterName", System::String, ()>(a1) }
    fn get_size(self) -> i32 { self.virt0::<"get_Size", i32>() }
    fn set_size(self, a1: i32) { self.instance1::<"set_Size", i32, ()>(a1) }
    fn get_source_column(self) -> System::String { self.virt0::<"get_SourceColumn", System::String>() }
    fn set_source_column(self, a1: System::String) { self.instance1::<"set_SourceColumn", System::String, ()>(a1) }
    fn get_source_column_null_mapping(self) -> bool { self.virt0::<"get_SourceColumnNullMapping", bool>() }
    fn set_source_column_null_mapping(self, a1: bool) { self.instance1::<"set_SourceColumnNullMapping", bool, ()>(a1) }
    fn get_value(self) -> System::Object { self.virt0::<"get_Value", System::Object>() }
    fn set_value(self, a1: System::Object) { self.instance1::<"set_Value", System::Object, ()>(a1) }
    fn reset_db_type(self) { self.virt0::<"ResetDbType", ()>() }
    fn reset_sqlite_type(self) { self.virt0::<"ResetSqliteType", ()>() }
    fn new() -> Self { Self::ctor0() }
}
pub type SqliteParameterCollection =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"Microsoft.Data.Sqlite","Microsoft.Data.Sqlite.SqliteParameterCollection">;
use super::super::super::*;
pub trait SqliteParameterCollection_Methods {
    fn get_count(self) -> i32;
    fn get_sync_root(self) -> System::Object;
    fn get_item(self, a1: i32) -> Microsoft::Data::Sqlite::SqliteParameter;
    fn set_item(self, a1: i32, a2: Microsoft::Data::Sqlite::SqliteParameter);
    fn add(self, a1: System::Object) -> i32;
    fn add_range(self, a1: System::Array);
    fn add_with_value(self, a1: System::String, a2: System::Object) -> Microsoft::Data::Sqlite::SqliteParameter;
    fn clear(self);
    fn contains(self, a1: System::Object) -> bool;
    fn copy_to(self, a1: System::Array, a2: i32);
    fn get_enumerator(self) -> System::Collections::IEnumerator;
    fn index_of(self, a1: System::Object) -> i32;
    fn insert(self, a1: i32, a2: System::Object);
    fn remove(self, a1: System::Object);
    fn remove_at(self, a1: i32);
}
impl SqliteParameterCollection_Methods for SqliteParameterCollection {
    fn get_count(self) -> i32 { self.virt0::<"get_Count", i32>() }
    fn get_sync_root(self) -> System::Object { self.virt0::<"get_SyncRoot", System::Object>() }
    fn get_item(self, a1: i32) -> Microsoft::Data::Sqlite::SqliteParameter { self.instance1::<"get_Item", i32, Microsoft::Data::Sqlite::SqliteParameter>(a1) }
    fn set_item(self, a1: i32, a2: Microsoft::Data::Sqlite::SqliteParameter) { self.instance2::<"set_Item", i32, Microsoft::Data::Sqlite::SqliteParameter, ()>(a1, a2) }
    fn add(self, a1: System::Object) -> i32 { self.instance1::<"Add", System::Object, i32>(a1) }
    fn add_range(self, a1: System::Array) { self.instance1::<"AddRange", System::Array, ()>(a1) }
    fn add_with_value(self, a1: System::String, a2: System::Object) -> Microsoft::Data::Sqlite::SqliteParameter { self.instance2::<"AddWithValue", System::String, System::Object, Microsoft::Data::Sqlite::SqliteParameter>(a1, a2) }
    fn clear(self) { self.virt0::<"Clear", ()>() }
    fn contains(self, a1: System::Object) -> bool { self.instance1::<"Contains", System::Object, bool>(a1) }
    fn copy_to(self, a1: System::Array, a2: i32) { self.instance2::<"CopyTo", System::Array, i32, ()>(a1, a2) }
    fn get_enumerator(self) -> System::Collections::IEnumerator { self.virt0::<"GetEnumerator", System::Collections::IEnumerator>() }
    fn index_of(self, a1: System::Object) -> i32 { self.instance1::<"IndexOf", System::Object, i32>(a1) }
    fn insert(self, a1: i32, a2: System::Object) { self.instance2::<"Insert", i32, System::Object, ()>(a1, a2) }
    fn remove(self, a1: System::Object) { self.instance1::<"Remove", System::Object, ()>(a1) }
    fn remove_at(self, a1: i32) { self.instance1::<"RemoveAt", i32, ()>(a1) }
}
pub type SqliteTransaction =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"Microsoft.Data.Sqlite","Microsoft.Data.Sqlite.SqliteTransaction">;
use super::super::super::*;
pub trait SqliteTransaction_Methods {
    fn get_connection(self) -> Microsoft::Data::Sqlite::SqliteConnection;
    fn commit(self);
    fn rollback(self);
    fn get_supports_savepoints(self) -> bool;
    fn save(self, a1: System::String);
    fn release(self, a1: System::String);
}
impl SqliteTransaction_Methods for SqliteTransaction {
    fn get_connection(self) -> Microsoft::Data::Sqlite::SqliteConnection { self.virt0::<"get_Connection", Microsoft::Data::Sqlite::SqliteConnection>() }
    fn commit(self) { self.virt0::<"Commit", ()>() }
    fn rollback(self) { self.virt0::<"Rollback", ()>() }
    fn get_supports_savepoints(self) -> bool { self.virt0::<"get_SupportsSavepoints", bool>() }
    fn save(self, a1: System::String) { self.instance1::<"Save", System::String, ()>(a1) }
    fn release(self, a1: System::String) { self.instance1::<"Release", System::String, ()>(a1) }
}
}
}
}
