using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Mycorrhiza.Interop.Helpers;

/// <summary>
/// Owns the native release callback for one Rust-produced asynchronous stream.
/// </summary>
/// <remarks>
/// The callback is exchanged with <see langword="null"/> before it is invoked, so normal
/// completion, cancellation, early disposal, and finalization all converge on exactly one release.
/// </remarks>
public sealed class RustStreamLease
{
    private readonly long _id;
    private Action<long>? _release;

    public RustStreamLease(long id, Action<long> release)
    {
        _id = id;
        _release = release ?? throw new ArgumentNullException(nameof(release));
    }

    public void Release()
    {
        Action<long>? release = Interlocked.Exchange(ref _release, null);
        if (release is null)
        {
            return;
        }

        release(_id);
        GC.SuppressFinalize(this);
    }

    ~RustStreamLease()
    {
        try
        {
            Release();
        }
        catch
        {
            // A finalizer must never terminate the process. The native callback generated by
            // mycorrhiza is non-throwing; this is defense against a malformed external caller.
        }
    }
}

/// <summary>
/// A single-consumer adapter over a channel-backed Rust producer.
/// </summary>
/// <remarks>
/// The inner BCL iterator supplies the real asynchronous <see cref="ValueTask{TResult}"/>
/// implementation. This adapter only couples its lifetime to Rust producer cancellation.
/// </remarks>
public sealed class RustAsyncEnumerable<T> : IAsyncEnumerable<T>
{
    private readonly IAsyncEnumerable<T> _inner;
    private readonly RustStreamLease _lease;
    private int _enumerationStarted;

    public RustAsyncEnumerable(IAsyncEnumerable<T> inner, RustStreamLease lease)
    {
        _inner = inner ?? throw new ArgumentNullException(nameof(inner));
        _lease = lease ?? throw new ArgumentNullException(nameof(lease));
    }

    public IAsyncEnumerator<T> GetAsyncEnumerator(
        CancellationToken cancellationToken = default)
    {
        if (Interlocked.Exchange(ref _enumerationStarted, 1) != 0)
        {
            throw new InvalidOperationException(
                "A Rust-produced async stream is single-consumer and cannot be enumerated twice.");
        }

        try
        {
            return new Enumerator(_inner.GetAsyncEnumerator(cancellationToken), _lease);
        }
        catch
        {
            _lease.Release();
            throw;
        }
    }

    private sealed class Enumerator : IAsyncEnumerator<T>
    {
        private readonly IAsyncEnumerator<T> _inner;
        private readonly RustStreamLease _lease;

        public Enumerator(IAsyncEnumerator<T> inner, RustStreamLease lease)
        {
            _inner = inner;
            _lease = lease;
        }

        public T Current => _inner.Current;

        public async ValueTask<bool> MoveNextAsync()
        {
            try
            {
                bool moved = await _inner.MoveNextAsync().ConfigureAwait(false);
                if (!moved)
                {
                    _lease.Release();
                }
                return moved;
            }
            catch
            {
                _lease.Release();
                throw;
            }
        }

        public async ValueTask DisposeAsync()
        {
            try
            {
                await _inner.DisposeAsync().ConfigureAwait(false);
            }
            finally
            {
                _lease.Release();
            }
        }
    }
}
