//! Comptime type-export intrinsics — the `.NET ← Rust` *define-a-managed-class* path.
//!
//! These functions are never executed (their bodies diverge). They exist so that a
//! `rustc_codegen_clr_comptime_entrypoint` fn — generated by `#[dotnet_class]` (or the older
//! declarative `dotnet_typedef!`) — can *call* them in sequence; the backend's comptime interpreter
//! (`src/comptime.rs`) reads that fn's MIR and registers a real `ClassDef` into the produced assembly.
//! The metadata (class name, field/method names, super-class) rides in the `&'static str` const
//! generics; the field/return *types* ride in the type generics.
//!
//! The opaque `black_box(true)` loop body is deliberate: a plain `abort()` would let the optimizer see
//! each call as diverging and eliminate every following call in the entrypoint (so the interpreter
//! would see an empty class). The opaque loop keeps the whole call sequence in the entrypoint's MIR.

use core::hint::black_box;

/// A managed class under construction. Never really materialized — only threaded between the magic
/// calls so the interpreter can follow the MIR data-flow.
#[derive(Clone, Copy)]
pub struct ClassDef {
    _prevent_construction: usize,
}

macro_rules! diverge {
    () => {{
        black_box(());
        loop {
            if black_box(true) {
                core::intrinsics::abort()
            }
        }
    }};
}

/// Begin a new managed class `NAME : [INHERITS_ASM]INHERITS` (`IS_VALUETYPE` selects struct vs
/// class).
///
/// `HAS_TYPE_KIND_OPINION` distinguishes an AUTHORITATIVE `IS_VALUETYPE` (from `#[dotnet_class]`'s
/// own `value_type = ...` attribute, or `#[dotnet_interface]`'s always-`false`) from a re-opening
/// entrypoint that has NO real opinion (`#[dotnet_methods]`'s impl-block entrypoint has no access
/// to the original struct's `value_type` attribute — same reasoning as `INHERITS` being emptyable
/// for "no opinion" on the base class; a bare `bool` has no null value, so this needs its own
/// flag). The backend's `finish_type` looks up an existing class BY NAME ALONE (never by an
/// is_valuetype-baked `ClassRef`) precisely so a no-opinion `IS_VALUETYPE=false` placeholder from a
/// re-opening entrypoint can never desync the lookup key from a `value_type = true` class's real
/// identity and silently register a second, phantom same-named `ClassDef` — see
/// `cilly::ir::class::ClassDef::set_is_valuetype`'s doc for the exact hazard this mirrors
/// (`set_extends`'s sibling).
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_new_typedef<
    const NAME: &'static str,
    const IS_VALUETYPE: bool,
    const INHERITS_ASM: &'static str,
    const INHERITS: &'static str,
    const HAS_TYPE_KIND_OPINION: bool,
>() -> ClassDef {
    diverge!()
}

/// Add a field `FNAME: T` to the class.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_field_def<T, const FNAME: &'static str>(class: ClassDef) -> ClassDef {
    diverge!()
}

/// Add a **static** field `FNAME: T` to the class — a genuine ECMA-335 `static` `Field` row
/// (§II.23.1.5: `Public | Static`, zero/`default(T)`-initialized, no `.cctor` needed — the CLR's
/// own beforefieldinit zero-init covers it), so a managed caller sees `ClassName.FNAME` directly,
/// no accessor method needed (unlike instance fields, which stay private behind `read_*`/`set_*`).
/// Also emits `static T get_FNAME()` / `static void set_FNAME(T)` so Rust code can read/write it
/// too — call them the same way any other static method on this class is called (`<Name>Handle::
/// static0::<"get_FNAME", T>()` / `static1::<"set_FNAME", T, ()>(value)`), no separate intrinsic
/// needed. Unlike `rustc_codegen_clr_add_field_def`, this is NOT part of the primary-ctor's field
/// list — a static field is per-TYPE state, not per-instance.
///
/// Scoped to a PLAIN mutable static (not `const`, not `[ThreadStatic]`) — `cilly::StaticFieldDef`
/// already models both (`is_const`/`is_tls`), so extending this intrinsic to accept them is a
/// natural, low-risk follow-up; this first cut covers the common "shared/global state" case.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_static_field_def<T, const FNAME: &'static str>(
    class: ClassDef,
) -> ClassDef {
    diverge!()
}

/// Add a virtual (instance) method `FNAME` aliasing the ordinary Rust fn `fn_type` (which takes the
/// receiver as its first explicit argument).
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_method_def<
    const VIS: &'static str,
    const MODIFIERS: &'static str,
    const FNAME: &'static str,
    FnType,
>(
    class: ClassDef,
    fn_type: FnType,
) -> ClassDef {
    diverge!()
}

/// Marks the virtual method most recently added via [`rustc_codegen_clr_add_method_def`] (in this
/// same comptime entrypoint's call sequence — must come immediately after that call, before any
/// other `add_method_def`) as an explicit ECMA-335 `.override` of `[BASE_ASM]BASE_TYPE`'s
/// same-named virtual — e.g. `System.Object.ToString()` — instead of relying on implicit
/// name+signature binding (the mechanism `implements=` uses for interfaces, which has no
/// pre-existing vtable slot to land in and so doesn't need this). Overriding a *base class*
/// virtual must land in that exact slot, which implicit binding can silently get wrong (creating
/// a new slot — a shadow method — instead of an override) if the signature doesn't match exactly.
///
/// Scoped intentionally narrow (see `docs/MYCORRHIZA_ERGONOMICS_BACKLOG.md`'s Tier C finding #1
/// for the full discussion): proven for exactly one well-known, parameterless, unsealed base
/// virtual (`System.Object.ToString()`). General base-class wrapping (a framework type with a
/// non-trivial constructor, protected members, `sealed` methods the CLR would reject at load
/// time) is a separate, larger, unaddressed problem — do not assume this covers it.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_mark_last_method_override<
    const BASE_ASM: &'static str,
    const BASE_TYPE: &'static str,
>(
    class: ClassDef,
) -> ClassDef {
    diverge!()
}

/// Marks the method most recently added via [`rustc_codegen_clr_add_method_def`] (or, on an
/// interface marked with [`rustc_codegen_clr_mark_interface`], via
/// [`rustc_codegen_clr_add_abstract_method_def`] — the accessor is then an abstract, body-less
/// interface member) as the `add_*` half of a `.NET` event named `EVENT_NAME` (e.g. `event_name =
/// "Changed"` for a C# `event Action<T> Changed`). Must come immediately after that call, before
/// any other member-adding call. Pair with
/// [`rustc_codegen_clr_mark_last_method_event_remove`] on the matching
/// `remove_*` method — both must be present for the event to be emitted (see
/// `EventDef`'s doc in `cilly` for the exact shape). The delegate type is inferred from the
/// method's own second parameter (the value being subscribed/unsubscribed), not from a string —
/// there is nothing to spell out separately.
///
/// Scoped intentionally narrow (see `docs/MYCORRHIZA_ERGONOMICS_BACKLOG.md`'s Tier C finding #5):
/// the synthesized `add_`/`remove_` bodies are ordinary methods you write yourself (typically
/// calling `Delegate.Combine`/`Delegate.Remove` on a backing delegate-typed field) — this
/// intrinsic only links their names into the event metadata, it does not synthesize thread-safe
/// (`Interlocked.CompareExchange`-based) bodies for you.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_mark_last_method_event_add<const EVENT_NAME: &'static str>(
    class: ClassDef,
) -> ClassDef {
    diverge!()
}

/// The `remove_*` counterpart to [`rustc_codegen_clr_mark_last_method_event_add`] — see that
/// function's doc.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_mark_last_method_event_remove<const EVENT_NAME: &'static str>(
    class: ClassDef,
) -> ClassDef {
    diverge!()
}

/// Add a `static` method `FNAME` aliasing the ordinary Rust fn `fn_type`. Unlike
/// [`rustc_codegen_clr_add_method_def`], a static method has no receiver — its parameter list is the
/// Rust fn's signature verbatim — so a managed caller invokes it as `<Class>.FNAME(…)`.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_static_method_def<const FNAME: &'static str, FnType>(
    class: ClassDef,
    fn_type: FnType,
) -> ClassDef {
    diverge!()
}

/// Request a *primary constructor*: a field-initializing `.ctor(field0, field1, …)` over the declared
/// fields, in declaration order — so a managed caller (C#) can `new <Name>(…)` and get an instance
/// with its fields set. (The backend synthesizes the ctor body; no Rust fn is aliased.)
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_primary_ctor(class: ClassDef) -> ClassDef {
    diverge!()
}

/// Request an additional *parameterless* constructor `.ctor()` (in addition to any primary ctor),
/// which chains to the base ctor and zero-initializes the fields — so a managed caller can
/// `new <Name>()` and get a default instance. Overloads the primary ctor (distinct arity), giving the
/// class multiple constructors. (The backend synthesizes the body; no Rust fn is aliased.)
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_default_ctor(class: ClassDef) -> ClassDef {
    diverge!()
}

/// Request that each declared field also gets a public `set_<field>(value)` mutator (a paired setter
/// for the `read_<field>` accessor the primary ctor already emits) — so a managed caller can both
/// observe and update the field state through methods. (The backend synthesizes the bodies.)
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_field_setters(class: ClassDef) -> ClassDef {
    diverge!()
}

/// Request that each declared field also gets a `get_<Field>`/`set_<Field>` accessor pair linked
/// into a real `.NET` property (§II.22.34 `Property` + `SpecialName` + `MethodSemantics` — the same
/// shape [`rustc_codegen_clr_mark_last_abstract_property_get`]/`_set` build for an interface, but for
/// an ordinary field-backed concrete class): reflection-based consumers that specifically scan
/// `Type.GetProperties()` (e.g. EF Core's default entity-type discovery convention, which needs a
/// genuine `PropertyInfo` to map a column) see a real property, not just a same-shaped pair of
/// ordinary methods. The property name is the field name, capitalized (`id` -> `Id`).
///
/// Deliberately a SEPARATE opt-in from [`rustc_codegen_clr_add_field_setters`], not a variant of it:
/// once a method is linked as a property accessor via `MethodSemantics`, C#/Roslyn REJECTS
/// explicitly calling it by name (`CS0571: cannot explicitly call operator or accessor`) — so a
/// class whose `read_<field>`/`set_<field>` accessors existing consumers already call explicitly
/// (e.g. `cd_typedef`'s `Counter`) must keep using `add_field_setters` alone; this intrinsic instead
/// emits its own `get_<Field>`/`set_<Field>` pair, distinct methods a caller reaches only through
/// the property (`widget.Id`, not `widget.get_Id()`). (The backend synthesizes the bodies.)
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_field_properties(class: ClassDef) -> ClassDef {
    diverge!()
}

/// Declare that this class implements the managed interface `[IFACE_ASM]IFACE` (an `implements` clause).
/// The class must expose a public virtual method matching each interface member by name+signature —
/// those are the ordinary `rustc_codegen_clr_add_method_def` aliases — and CLR binds them implicitly,
/// so no explicit `.override` is emitted. Call once per interface. This lets a Rust-defined managed
/// type satisfy an interface defined in a *third* assembly (e.g. a C# consumer's own `IService`), so it
/// can be used polymorphically / injected into a DI container on the .NET side.
///
/// On a class marked [`rustc_codegen_clr_mark_interface`], this instead declares a BASE interface
/// (`interface IDerived : IBase` — ECMA-335 §II.10.1.3 models interface inheritance as the very
/// same `InterfaceImpl` rows, never `Extends`); `#[dotnet_interface]` lowers each supertrait to one
/// of these calls with an empty `IFACE_ASM` (same final assembly). A same-assembly `IFACE` that
/// doesn't resolve to a registered type, or resolves to a non-interface class, is a loud export-time
/// error (the PE writer's Pass 1.5 validation).
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_interface_impl<
    const IFACE_ASM: &'static str,
    const IFACE: &'static str,
>(
    class: ClassDef,
) -> ClassDef {
    diverge!()
}

/// Like [`rustc_codegen_clr_add_interface_impl`], but for a *generic* managed interface with one
/// generic parameter (e.g. `IEnumerator<T>`, `IAsyncEnumerator<T>`, `IEquatable<T>`) bound to a
/// concrete external type `[GENERIC_ASM]GENERIC_TYPE` — referenced exactly like `IFACE_ASM`/`IFACE`
/// or `extends=`'s own superclass reference, not derived from any Rust type. `GENERIC_IS_VALUETYPE`
/// must be `true` for a BCL value type argument (`System.Int32`, a user struct, …) and `false` for
/// a reference type (`System.String`, a user class, …) — since the argument is a plain string name
/// with no backing Rust type to infer this from (unlike ordinary field/method types, which get it
/// from `get_type`), an unbound generic argument's CLASS/VALUETYPE encoding must be supplied
/// explicitly or the emitted `GENERICINST` signature blob tags it wrong. Only single-generic-
/// parameter interfaces are expressible this way today (the overwhelmingly common arity in the
/// BCL); a multi-argument interface (e.g. `IDictionary<K,V>`) isn't. Call once per interface.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_generic_interface_impl<
    const IFACE_ASM: &'static str,
    const IFACE: &'static str,
    const GENERIC_ASM: &'static str,
    const GENERIC_TYPE: &'static str,
    const GENERIC_IS_VALUETYPE: bool,
>(
    class: ClassDef,
) -> ClassDef {
    diverge!()
}

/// Attach one general ECMA-335 `CustomAttribute` (§II.21/§II.23.3) to the class-under-construction
/// — the general mechanism `#[dotnet_class(attr(...))]` lowers to, one call per attribute. `SPEC`
/// is a single encoded string (built by the `dotnet_macros` proc-macro at compile time — never
/// hand-written) carrying the attribute type reference, positional constructor args, and named
/// property args in one packed field, using ASCII control-character delimiters (`\x1E` record
/// separator between top-level fields, `\x1D` group separator between list items, `\x1C` between a
/// named arg's name and value) — chosen specifically because they can never appear in ordinary
/// source text, so no escaping is needed; `dotnet_macros` rejects any literal that contains one.
/// Each arg is tagged `s:`/`b:`/`i:`/`l:` (string/bool/i32/i64) — see `src/comptime.rs`'s decoder
/// for the authoritative format. This indirection (one packed `&'static str` instead of N
/// differently-shaped const generics) exists because a single intrinsic's generic arity is fixed,
/// but a real attribute can carry any number of args of any of these types.
///
/// A denylisted attribute TYPE (one CoreCLR's own loader/JIT treats as runtime-semantic — layout
/// or calling-convention affecting, e.g. `InlineArrayAttribute`, `UnmanagedCallersOnlyAttribute`,
/// `StructLayoutAttribute` — see `dotnet_macros`' `ATTR_DENYLIST`) is rejected as a Rust COMPILE
/// error by `#[dotnet_class]` itself, before this intrinsic is ever emitted; the backend
/// interpreter re-checks the same denylist as defense-in-depth (`src/comptime.rs`).
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_custom_attr<const SPEC: &'static str>(class: ClassDef) -> ClassDef {
    diverge!()
}

/// Marks the class-under-construction as a genuine ECMA-335 `interface` `TypeDef` (`Interface`+
/// `Abstract` flags, NO base type) rather than an ordinary class — used by `#[dotnet_interface]` to
/// turn a Rust `trait` into a C#-consumable interface. Call once, right after `new_typedef` (whose
/// superclass args must be empty — an interface has no base). Every method added afterward must be
/// an abstract member via [`rustc_codegen_clr_add_abstract_method_def`] (interface members have no
/// body). The resulting interface can be implemented from C# (`class Foo : IMyInterface`) or from a
/// Rust `#[dotnet_class]` via `implements = "IMyInterface"`.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_mark_interface(class: ClassDef) -> ClassDef {
    diverge!()
}

/// Declares the type-under-construction's generic parameters — `NAMES` is a `;`-separated list of
/// the declared parameter names in declaration order (e.g. `"T"` or `"K;V"`), the same separator
/// convention as `#[dotnet_class]`'s `implements=` list. Emitted by `#[dotnet_interface]` on a
/// generic trait (`trait IBox<T>`), whose `NAME` (in [`rustc_codegen_clr_new_typedef`]) already
/// carries the CLS backtick-arity suffix (`IBox`1`); the backend emits one ECMA-335
/// `GenericParam` row (§II.22.20) per name on the type's own `TypeDef`. Only valid together with
/// [`rustc_codegen_clr_mark_interface`] — a generic *class* definition is rejected loudly at
/// `finish_type` (the historical no-explicit-layout-on-.NET-generics ban applies to classes;
/// an interface has no layout). Member signatures reference the parameters positionally via
/// `RustcCLRInteropTypeGeneric<N>` markers (`ELEMENT_TYPE_VAR`, C#'s `T` in `IBox<T>`).
///
/// Substring-dispatch safety (see `src/comptime.rs`'s `contains()` chain): `set_type_generics`
/// neither contains nor is contained by any sibling intrinsic's needle (audited against the full
/// chain — no other intrinsic contains `set_type` or `type_generics`).
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_set_type_generics<const NAMES: &'static str>(
    class: ClassDef,
) -> ClassDef {
    diverge!()
}

/// Add an **abstract** (no-body) instance method `FNAME` to an interface (see
/// [`rustc_codegen_clr_mark_interface`]). Unlike [`rustc_codegen_clr_add_method_def`], `sig_carrier`
/// is NOT aliased/codegen'd — it is a signature-only placeholder fn (generated by
/// `#[dotnet_interface]`) whose type signature defines the abstract member's parameters and return
/// type. Its first parameter is the interface's own handle type (the implicit `this` receiver, as
/// with a virtual method); a C# implementor / caller sees the signature with the receiver dropped
/// (`ret FNAME(params…)`).
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_abstract_method_def<const FNAME: &'static str, FnType>(
    class: ClassDef,
    sig_carrier: FnType,
) -> ClassDef {
    diverge!()
}

/// Add a **generic abstract** (no-body) instance method `FNAME` to an interface (see
/// [`rustc_codegen_clr_mark_interface`]) — a genuine ECMA-335 generic method DEFINITION
/// (`T Echo<T>(T value)`): the signature blob carries `SIG_GENERIC` + a `GenParamCount`, one
/// method-owned `GenericParam` row is emitted per declared parameter, and C# sees/implements it
/// as an ordinary generic interface method. `GENERIC_PARAMS` is the `;`-separated ordered
/// type-parameter NAME list (`"T"`, `"K;V"`, …) — the same `;`-list convention as
/// [`rustc_codegen_clr_set_type_generics`]. Like [`rustc_codegen_clr_add_abstract_method_def`],
/// `sig_carrier` is a signature-only placeholder fn (generated by `#[dotnet_interface]`, never
/// aliased/codegen'd) whose first parameter is the interface's own handle (the implicit `this`
/// receiver); a parameter/return position naming the method's `N`-th generic parameter is spelled
/// [`crate::intrinsics::RustcCLRInteropMethodGeneric<N>`] in the carrier (lowered to
/// `ELEMENT_TYPE_MVAR N`, the member's `!!N` position — the METHOD-generic dual of the
/// `RustcCLRInteropTypeGeneric<N>`/`!N` marker a generic *interface*'s members use).
///
/// Substring-dispatch safety (see `src/comptime.rs`'s `contains()` chain):
/// `add_generic_abstract_method_def` neither contains nor is contained by `add_method_def`,
/// `add_abstract_method_def`, `add_static_method_def`, `add_static_abstract_method_def`,
/// `add_default_method_def`, `add_generic_interface_impl`, or `set_type_generics` (the
/// `generic_abstract_` infix breaks every containment; audited against the full chain).
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_generic_abstract_method_def<
    const FNAME: &'static str,
    const GENERIC_PARAMS: &'static str,
    FnType,
>(
    class: ClassDef,
    sig_carrier: FnType,
) -> ClassDef {
    diverge!()
}

/// Add a **default interface method** (DIM, CoreCLR 3.0+) `FNAME` to an interface (see
/// [`rustc_codegen_clr_mark_interface`]): a virtual, NON-abstract member with a real IL body on
/// the interface `TypeDef` itself, inherited by any implementing class that omits the member and
/// overridden by one that defines it (ordinary virtual dispatch). Unlike
/// [`rustc_codegen_clr_add_abstract_method_def`]'s signature-only carrier, `target` here IS
/// aliased and codegen'd (exactly like [`rustc_codegen_clr_add_method_def`]'s target): it is the
/// lifted default body `#[dotnet_interface]` generates from a trait method's default block, and
/// its first parameter is the interface's own handle (the implicit `this` receiver). Because the
/// target has a real body, it needs a `#[used]` KEEP anchor to survive the mono-collector — the
/// macro emits one.
///
/// Substring-dispatch safety (see `src/comptime.rs`'s `contains()` chain):
/// `add_default_method_def` neither contains nor is contained by `add_method_def`,
/// `add_abstract_method_def`, `add_static_abstract_method_def`, `add_static_method_def`, or
/// `add_default_ctor` (the `default_` infix / `method_def` tail break every containment;
/// audited against the full chain).
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_default_method_def<const FNAME: &'static str, FnType>(
    class: ClassDef,
    target: FnType,
) -> ClassDef {
    diverge!()
}

/// Add a **`static abstract`** (no-body) interface member `FNAME` to an interface (see
/// [`rustc_codegen_clr_mark_interface`]) — the .NET 7+ *static virtual members in interfaces*
/// shape (`INumber<T>`-style generic math: C# implements it as `public static int FNAME(…)` and
/// dispatches generically via `T.FNAME(…)` under a `where T : IFace` constraint). Like
/// [`rustc_codegen_clr_add_abstract_method_def`], `sig_carrier` is a signature-only placeholder fn
/// (generated by `#[dotnet_interface]` for a trait fn with NO `self` receiver) that is never
/// aliased/codegen'd — but unlike the instance form it has NO receiver parameter at all: its
/// signature is the member's C#-visible parameter list verbatim. Declaration-only surface: Rust
/// code cannot *call* a static abstract member (that needs a `constrained.` generic call the
/// backend doesn't emit); the consumer side (C#) implements and dispatches it.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_static_abstract_method_def<const FNAME: &'static str, FnType>(
    class: ClassDef,
    sig_carrier: FnType,
) -> ClassDef {
    diverge!()
}

/// Marks parameters of the LAST-added **abstract instance** interface member (the immediately
/// preceding [`rustc_codegen_clr_add_abstract_method_def`] call in the same entrypoint's MIR
/// sequence — the same "mark the LAST member" contract as
/// [`rustc_codegen_clr_mark_last_method_override`]) as C# **`out`** parameters. `OUT_PARAMS` is a
/// comma-separated list of 1-based parameter positions counted among the member's C#-visible
/// (receiver-stripped) parameters — e.g. `"1,3"`. Each named position must be a `&mut T` carrier
/// parameter: the backend lowers it to a managed byref (`ELEMENT_TYPE_BYREF`) and stamps
/// `ParamAttributes.Out` (0x0002) on its `Param` row, which is exactly the metadata shape csc
/// reads back as `out T` (a byref param with no flags reads back as `ref T`). Emitted by
/// `#[dotnet_interface]` for `#[dotnet_out]`-marked parameters; the macro guarantees every listed
/// position is `&mut T` and instance-membered, so the backend's validation panics are
/// unreachable-from-the-macro asserts, not user-facing errors.
///
/// Substring-dispatch safety (see `src/comptime.rs`'s `contains()` chain): this name neither
/// contains nor is contained by any sibling intrinsic's needle (`mark_last_abstract_method` vs
/// `mark_last_method_override`/`mark_last_method_event_*` — the `abstract_` infix breaks every
/// containment; audited against the full chain).
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_mark_last_abstract_method_out_params<const OUT_PARAMS: &'static str>(
    class: ClassDef,
) -> ClassDef {
    diverge!()
}

/// Marks the LAST-added **abstract instance** interface member (the immediately preceding
/// [`rustc_codegen_clr_add_abstract_method_def`] call in the same entrypoint's MIR sequence —
/// the same "mark the LAST member" contract as
/// [`rustc_codegen_clr_mark_last_abstract_method_out_params`]) as the **getter** of a `.NET`
/// property named `PROP_NAME` (e.g. `PROP_NAME = "Volume"` for a C# `int Volume { get; … }`).
/// Emitted by `#[dotnet_property]` on a `get_<Prop>` trait fn inside `#[dotnet_interface]`; the
/// property's value type is inferred from the accessor's own signature (the getter's return
/// type), never spelled separately. Pair with
/// [`rustc_codegen_clr_mark_last_abstract_property_set`] on the matching `set_<Prop>` accessor
/// for a read-write property; a getter alone declares a get-only property. A setter WITHOUT a
/// getter (a write-only property) is rejected at the macro level; if a hand-rolled entrypoint
/// produces one anyway, `finish_type` panics with a clear message. The backend emits the
/// §II.22.34 `Property` + §II.22.35 `PropertyMap` rows and a `MethodSemantics` `Getter` (0x2)
/// row over the abstract accessor, and stamps `SpecialName` on it (Roslyn's own accessor shape).
///
/// Substring-dispatch safety (see `src/comptime.rs`'s `contains()` chain):
/// `mark_last_abstract_property_get` neither contains nor is contained by any sibling
/// intrinsic's needle (`mark_last_abstract_method_out_params` diverges at `method_`/`property_`;
/// `mark_last_method_*` diverges at `abstract_`; `_get`/`_set` diverge from each other; audited
/// against the full chain).
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_mark_last_abstract_property_get<const PROP_NAME: &'static str>(
    class: ClassDef,
) -> ClassDef {
    diverge!()
}

/// The **setter** counterpart to [`rustc_codegen_clr_mark_last_abstract_property_get`] — marks
/// the LAST-added abstract instance member as the `set_<Prop>` accessor (`MethodSemantics`
/// `Setter`, 0x1). The property's value type is the setter's single non-receiver parameter; it
/// must agree with the getter's return type, or `finish_type` panics with a clear message. See
/// the getter intrinsic's doc for the full contract.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_mark_last_abstract_property_set<const PROP_NAME: &'static str>(
    class: ClassDef,
) -> ClassDef {
    diverge!()
}

/// Finish the class: register it (and its methods / primary ctor) into the assembly.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_finish_type(class: ClassDef) {
    diverge!()
}
