//! Comptime type-export intrinsics — the `.NET ← Rust` *define-a-managed-class* path.
//!
//! These functions are never executed (their bodies diverge). They exist so that a
//! `rustc_codegen_clr_comptime_entrypoint` fn — generated by `#[dotnet_class]` (or the older
//! declarative `dotnet_typedef!`) — can *call* them in sequence; the backend's comptime interpreter
//! (`src/comptime.rs`) reads that fn's MIR and registers a real `ClassDef` into the produced assembly.
//! The metadata (class name, field/method names, super-class) rides in the `&'static str` const
//! generics; the field/return *types* ride in the type generics.
//!
//! The opaque `black_box(true)` loop body is deliberate: a plain `abort()` would let the optimizer see
//! each call as diverging and eliminate every following call in the entrypoint (so the interpreter
//! would see an empty class). The opaque loop keeps the whole call sequence in the entrypoint's MIR.

use core::hint::black_box;

/// A managed class under construction. Never really materialized — only threaded between the magic
/// calls so the interpreter can follow the MIR data-flow.
#[derive(Clone, Copy)]
pub struct ClassDef {
    _prevent_construction: usize,
}

macro_rules! diverge {
    () => {{
        black_box(());
        loop {
            if black_box(true) {
                core::intrinsics::abort()
            }
        }
    }};
}

/// Begin a new managed class `NAME : [INHERITS_ASM]INHERITS` (`IS_VALUETYPE` selects struct vs class).
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_new_typedef<
    const NAME: &'static str,
    const IS_VALUETYPE: bool,
    const INHERITS_ASM: &'static str,
    const INHERITS: &'static str,
>() -> ClassDef {
    diverge!()
}

/// Add a field `FNAME: T` to the class.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_field_def<T, const FNAME: &'static str>(class: ClassDef) -> ClassDef {
    diverge!()
}

/// Add a virtual (instance) method `FNAME` aliasing the ordinary Rust fn `fn_type` (which takes the
/// receiver as its first explicit argument).
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_method_def<
    const VIS: &'static str,
    const MODIFIERS: &'static str,
    const FNAME: &'static str,
    FnType,
>(
    class: ClassDef,
    fn_type: FnType,
) -> ClassDef {
    diverge!()
}

/// Add a `static` method `FNAME` aliasing the ordinary Rust fn `fn_type`. Unlike
/// [`rustc_codegen_clr_add_method_def`], a static method has no receiver — its parameter list is the
/// Rust fn's signature verbatim — so a managed caller invokes it as `<Class>.FNAME(…)`.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_static_method_def<const FNAME: &'static str, FnType>(
    class: ClassDef,
    fn_type: FnType,
) -> ClassDef {
    diverge!()
}

/// Request a *primary constructor*: a field-initializing `.ctor(field0, field1, …)` over the declared
/// fields, in declaration order — so a managed caller (C#) can `new <Name>(…)` and get an instance
/// with its fields set. (The backend synthesizes the ctor body; no Rust fn is aliased.)
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_primary_ctor(class: ClassDef) -> ClassDef {
    diverge!()
}

/// Request an additional *parameterless* constructor `.ctor()` (in addition to any primary ctor),
/// which chains to the base ctor and zero-initializes the fields — so a managed caller can
/// `new <Name>()` and get a default instance. Overloads the primary ctor (distinct arity), giving the
/// class multiple constructors. (The backend synthesizes the body; no Rust fn is aliased.)
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_default_ctor(class: ClassDef) -> ClassDef {
    diverge!()
}

/// Request that each declared field also gets a public `set_<field>(value)` mutator (a paired setter
/// for the `read_<field>` accessor the primary ctor already emits) — so a managed caller can both
/// observe and update the field state through methods. (The backend synthesizes the bodies.)
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_field_setters(class: ClassDef) -> ClassDef {
    diverge!()
}

/// Finish the class: register it (and its methods / primary ctor) into the assembly.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_finish_type(class: ClassDef) {
    diverge!()
}
