//! Comptime type-export intrinsics — the `.NET ← Rust` *define-a-managed-class* path.
//!
//! These functions are never executed (their bodies diverge). They exist so that a
//! `rustc_codegen_clr_comptime_entrypoint` fn — generated by `#[dotnet_class]` (or the older
//! declarative `dotnet_typedef!`) — can *call* them in sequence; the backend's comptime interpreter
//! (`src/comptime.rs`) reads that fn's MIR and registers a real `ClassDef` into the produced assembly.
//! The metadata (class name, field/method names, super-class) rides in the `&'static str` const
//! generics; the field/return *types* ride in the type generics.
//!
//! The opaque `black_box(true)` loop body is deliberate: a plain `abort()` would let the optimizer see
//! each call as diverging and eliminate every following call in the entrypoint (so the interpreter
//! would see an empty class). The opaque loop keeps the whole call sequence in the entrypoint's MIR.

use core::hint::black_box;

/// A managed class under construction. Never really materialized — only threaded between the magic
/// calls so the interpreter can follow the MIR data-flow.
#[derive(Clone, Copy)]
pub struct ClassDef {
    _prevent_construction: usize,
}

macro_rules! diverge {
    () => {{
        black_box(());
        loop {
            if black_box(true) {
                core::intrinsics::abort()
            }
        }
    }};
}

/// Begin a new managed class `NAME : [INHERITS_ASM]INHERITS` (`IS_VALUETYPE` selects struct vs class).
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_new_typedef<
    const NAME: &'static str,
    const IS_VALUETYPE: bool,
    const INHERITS_ASM: &'static str,
    const INHERITS: &'static str,
>() -> ClassDef {
    diverge!()
}

/// Add a field `FNAME: T` to the class.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_field_def<T, const FNAME: &'static str>(class: ClassDef) -> ClassDef {
    diverge!()
}

/// Add a virtual (instance) method `FNAME` aliasing the ordinary Rust fn `fn_type` (which takes the
/// receiver as its first explicit argument).
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_method_def<
    const VIS: &'static str,
    const MODIFIERS: &'static str,
    const FNAME: &'static str,
    FnType,
>(
    class: ClassDef,
    fn_type: FnType,
) -> ClassDef {
    diverge!()
}

/// Marks the virtual method most recently added via [`rustc_codegen_clr_add_method_def`] (in this
/// same comptime entrypoint's call sequence — must come immediately after that call, before any
/// other `add_method_def`) as an explicit ECMA-335 `.override` of `[BASE_ASM]BASE_TYPE`'s
/// same-named virtual — e.g. `System.Object.ToString()` — instead of relying on implicit
/// name+signature binding (the mechanism `implements=` uses for interfaces, which has no
/// pre-existing vtable slot to land in and so doesn't need this). Overriding a *base class*
/// virtual must land in that exact slot, which implicit binding can silently get wrong (creating
/// a new slot — a shadow method — instead of an override) if the signature doesn't match exactly.
///
/// Scoped intentionally narrow (see `docs/MYCORRHIZA_ERGONOMICS_BACKLOG.md`'s Tier C finding #1
/// for the full discussion): proven for exactly one well-known, parameterless, unsealed base
/// virtual (`System.Object.ToString()`). General base-class wrapping (a framework type with a
/// non-trivial constructor, protected members, `sealed` methods the CLR would reject at load
/// time) is a separate, larger, unaddressed problem — do not assume this covers it.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_mark_last_method_override<
    const BASE_ASM: &'static str,
    const BASE_TYPE: &'static str,
>(
    class: ClassDef,
) -> ClassDef {
    diverge!()
}

/// Marks the virtual method most recently added via [`rustc_codegen_clr_add_method_def`] as the
/// `add_*` half of a `.NET` event named `EVENT_NAME` (e.g. `event_name = "Changed"` for a C#
/// `event Action<T> Changed`). Must come immediately after that call, before any other
/// `add_method_def`. Pair with [`rustc_codegen_clr_mark_last_method_event_remove`] on the matching
/// `remove_*` method — both must be present for the event to be emitted (see
/// `EventDef`'s doc in `cilly` for the exact shape). The delegate type is inferred from the
/// method's own second parameter (the value being subscribed/unsubscribed), not from a string —
/// there is nothing to spell out separately.
///
/// Scoped intentionally narrow (see `docs/MYCORRHIZA_ERGONOMICS_BACKLOG.md`'s Tier C finding #5):
/// the synthesized `add_`/`remove_` bodies are ordinary methods you write yourself (typically
/// calling `Delegate.Combine`/`Delegate.Remove` on a backing delegate-typed field) — this
/// intrinsic only links their names into the event metadata, it does not synthesize thread-safe
/// (`Interlocked.CompareExchange`-based) bodies for you.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_mark_last_method_event_add<const EVENT_NAME: &'static str>(
    class: ClassDef,
) -> ClassDef {
    diverge!()
}

/// The `remove_*` counterpart to [`rustc_codegen_clr_mark_last_method_event_add`] — see that
/// function's doc.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_mark_last_method_event_remove<const EVENT_NAME: &'static str>(
    class: ClassDef,
) -> ClassDef {
    diverge!()
}

/// Add a `static` method `FNAME` aliasing the ordinary Rust fn `fn_type`. Unlike
/// [`rustc_codegen_clr_add_method_def`], a static method has no receiver — its parameter list is the
/// Rust fn's signature verbatim — so a managed caller invokes it as `<Class>.FNAME(…)`.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_static_method_def<const FNAME: &'static str, FnType>(
    class: ClassDef,
    fn_type: FnType,
) -> ClassDef {
    diverge!()
}

/// Request a *primary constructor*: a field-initializing `.ctor(field0, field1, …)` over the declared
/// fields, in declaration order — so a managed caller (C#) can `new <Name>(…)` and get an instance
/// with its fields set. (The backend synthesizes the ctor body; no Rust fn is aliased.)
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_primary_ctor(class: ClassDef) -> ClassDef {
    diverge!()
}

/// Request an additional *parameterless* constructor `.ctor()` (in addition to any primary ctor),
/// which chains to the base ctor and zero-initializes the fields — so a managed caller can
/// `new <Name>()` and get a default instance. Overloads the primary ctor (distinct arity), giving the
/// class multiple constructors. (The backend synthesizes the body; no Rust fn is aliased.)
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_default_ctor(class: ClassDef) -> ClassDef {
    diverge!()
}

/// Request that each declared field also gets a public `set_<field>(value)` mutator (a paired setter
/// for the `read_<field>` accessor the primary ctor already emits) — so a managed caller can both
/// observe and update the field state through methods. (The backend synthesizes the bodies.)
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_field_setters(class: ClassDef) -> ClassDef {
    diverge!()
}

/// Declare that this class implements the managed interface `[IFACE_ASM]IFACE` (an `implements` clause).
/// The class must expose a public virtual method matching each interface member by name+signature —
/// those are the ordinary `rustc_codegen_clr_add_method_def` aliases — and CLR binds them implicitly,
/// so no explicit `.override` is emitted. Call once per interface. This lets a Rust-defined managed
/// type satisfy an interface defined in a *third* assembly (e.g. a C# consumer's own `IService`), so it
/// can be used polymorphically / injected into a DI container on the .NET side.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_interface_impl<
    const IFACE_ASM: &'static str,
    const IFACE: &'static str,
>(
    class: ClassDef,
) -> ClassDef {
    diverge!()
}

/// Like [`rustc_codegen_clr_add_interface_impl`], but for a *generic* managed interface with one
/// generic parameter (e.g. `IEnumerator<T>`, `IAsyncEnumerator<T>`, `IEquatable<T>`) bound to a
/// concrete external type `[GENERIC_ASM]GENERIC_TYPE` — referenced exactly like `IFACE_ASM`/`IFACE`
/// or `extends=`'s own superclass reference, not derived from any Rust type. `GENERIC_IS_VALUETYPE`
/// must be `true` for a BCL value type argument (`System.Int32`, a user struct, …) and `false` for
/// a reference type (`System.String`, a user class, …) — since the argument is a plain string name
/// with no backing Rust type to infer this from (unlike ordinary field/method types, which get it
/// from `get_type`), an unbound generic argument's CLASS/VALUETYPE encoding must be supplied
/// explicitly or the emitted `GENERICINST` signature blob tags it wrong. Only single-generic-
/// parameter interfaces are expressible this way today (the overwhelmingly common arity in the
/// BCL); a multi-argument interface (e.g. `IDictionary<K,V>`) isn't. Call once per interface.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_add_generic_interface_impl<
    const IFACE_ASM: &'static str,
    const IFACE: &'static str,
    const GENERIC_ASM: &'static str,
    const GENERIC_TYPE: &'static str,
    const GENERIC_IS_VALUETYPE: bool,
>(
    class: ClassDef,
) -> ClassDef {
    diverge!()
}

/// Finish the class: register it (and its methods / primary ctor) into the assembly.
#[allow(unused_variables)]
#[inline(never)]
pub fn rustc_codegen_clr_finish_type(class: ClassDef) {
    diverge!()
}
