//! `dotnet_overlays` auto-apply — typed port of the bash `apply_overlays` (core
//! 651-724) using the `toml` crate.
//!
//! Three load-bearing crates (mio, socket2, tokio) need a small marked source overlay
//! that no cfg flip can supply. We redirect any present in the project's dep graph via
//! a generated `.cargo/config.toml` `paths = [ … ]` override — the user's tracked
//! Cargo.toml is never touched, and `paths` is graph-wide by crate NAME so it covers a
//! transitive dep (mio under tokio).

use std::fs;
use std::path::Path;

use anyhow::{Context as _, Result};
use serde::Deserialize;

use crate::context::Context;

#[derive(Debug, Deserialize)]
struct Registry {
    #[serde(default)]
    overlay: Vec<Overlay>,
}

#[derive(Debug, Deserialize)]
struct Overlay {
    name: String,
    version: String,
    dir: String,
}

/// Regenerate the crate's `.cargo/config.toml` from scratch with the overlay
/// paths-override, preserving the CRITICAL emit order, then warn on a lock mismatch.
pub fn apply(ctx: &Context) -> Result<()> {
    let reg_path = ctx.paths.overlays_root.join("REGISTRY.toml");
    if !reg_path.is_file() {
        eprintln!(
            "==> no overlay registry at {} (skipping auto-apply)",
            reg_path.display()
        );
        return Ok(());
    }
    let reg_text = fs::read_to_string(&reg_path)
        .with_context(|| format!("read {}", reg_path.display()))?;
    let reg: Registry =
        toml::from_str(&reg_text).with_context(|| format!("parse {}", reg_path.display()))?;

    // Build the paths list (one existing dir per overlay; cargo ignores entries whose
    // crate isn't in the graph, so emitting all overlays is safe).
    let mut paths_lines = String::new();
    for ov in &reg.overlay {
        let dir = ctx.paths.overlays_root.join(&ov.dir);
        if !dir.is_dir() {
            eprintln!("!! overlay dir missing: {}", dir.display());
            continue;
        }
        paths_lines.push_str(&format!("    \"{}\",\n", dir.display()));
    }

    // Regenerate .cargo/config.toml FROM SCRATCH. EMIT ORDER IS LOAD-BEARING: the
    // top-level `paths` key MUST precede any table header, or cargo silently drops it
    // (`unused config key`) and the override no-ops -> the crate resolves UNPATCHED ->
    // miscompile. So we write the string in this exact sequence (not toml::to_string,
    // which won't guarantee a top-level key precedes the tables).
    let cargo_dir = ctx.crate_dir.join(".cargo");
    fs::create_dir_all(&cargo_dir)
        .with_context(|| format!("mkdir -p {}", cargo_dir.display()))?;
    let config = format!(
        "# GENERATED by cargo dotnet (overlays::apply) — do not hand-edit.\n\
         paths = [\n{paths_lines}]\n\
         [build]\n\
         target = \"{spec}\"\n\
         [unstable]\n\
         build-std = [\"core\", \"alloc\", \"std\", \"panic_unwind\"]\n",
        spec = ctx.paths.target_spec.display(),
    );
    fs::write(cargo_dir.join("config.toml"), config)
        .with_context(|| format!("write {}", cargo_dir.join("config.toml").display()))?;
    eprintln!("==> regenerated .cargo/config.toml with dotnet_overlays paths override");

    // Verify each overlay's declared version against the locked version; warn loudly on
    // a mismatch (cargo would silently ignore the override -> miscompile risk).
    let lock = ctx.crate_dir.join("Cargo.lock");
    if lock.is_file() {
        warn_on_lock_mismatch(&lock, &reg)?;
    }
    Ok(())
}

/// Parse Cargo.lock and warn if an overlay's declared version != the locked version
/// (the "overlay silently not applied" footgun). The lock is TOML, so this replaces the
/// bash awk/paste scan with a typed parse.
fn warn_on_lock_mismatch(lock: &Path, reg: &Registry) -> Result<()> {
    #[derive(Deserialize)]
    struct Lock {
        #[serde(default)]
        package: Vec<Pkg>,
    }
    #[derive(Deserialize)]
    struct Pkg {
        name: String,
        version: String,
    }
    let text = fs::read_to_string(lock).with_context(|| format!("read {}", lock.display()))?;
    let parsed: Lock = match toml::from_str(&text) {
        Ok(l) => l,
        Err(_) => return Ok(()), // a malformed/partial lock isn't fatal to the build.
    };
    for ov in &reg.overlay {
        let Some(locked) = parsed
            .package
            .iter()
            .find(|p| p.name == ov.name)
            .map(|p| p.version.as_str())
        else {
            continue; // overlay crate not in this graph — fine, the paths entry is inert.
        };
        if locked == ov.version {
            eprintln!("==> overlay APPLIED: {} {} (locked {locked})", ov.name, ov.version);
        } else {
            eprintln!(
                "!! OVERLAY VERSION MISMATCH: {} overlay={} but Cargo.lock pins {locked}",
                ov.name, ov.version
            );
            eprintln!(
                "!! cargo will IGNORE the paths override for {} (footgun: overlay NOT applied).",
                ov.name
            );
            eprintln!(
                "!! Fix: refresh dotnet_overlays/{} to {locked} + bump REGISTRY.toml.",
                ov.name
            );
        }
    }
    Ok(())
}
