//! `dotnet_overlays` auto-apply — typed port of the bash `apply_overlays` (core
//! 651-724) using the `toml` crate.
//!
//! Three load-bearing crates (mio, socket2, tokio) need a small marked source overlay
//! that no cfg flip can supply. We redirect any present in the project's dep graph via
//! an explicit build-local Cargo config with a `paths = [ … ]` override — the user's tracked
//! Cargo.toml and user-owned Cargo config are never touched, and `paths` is graph-wide by crate NAME so it covers a
//! transitive dep (mio under tokio).

use std::collections::HashMap;
use std::fs;
use std::path::Path;
use std::process::Command;

use anyhow::{Context as _, Result};
use serde::Deserialize;
use sha2::{Digest, Sha256};

use crate::context::Context;

#[derive(Debug, Deserialize)]
struct Registry {
    #[serde(default)]
    overlay: Vec<Overlay>,
}

#[derive(Debug, Deserialize)]
struct Overlay {
    name: String,
    version: String,
    dir: String,
}

#[derive(Deserialize)]
struct Lock {
    #[serde(default)]
    package: Vec<Pkg>,
}
#[derive(Deserialize)]
struct Pkg {
    name: String,
    version: String,
}

fn toml_path_literal(path: &Path) -> String {
    // Path's Debug representation is a quoted, escaped string suitable for TOML on both Unix and
    // Windows. Display would emit `D:\...` with unescaped backslashes.
    format!("{path:?}")
}

/// Write a build-local Cargo config with the given (already-formatted) `paths` body plus
/// the dotnet target + build-std. EMIT ORDER IS LOAD-BEARING: the top-level `paths`
/// key MUST precede any table header, or cargo silently drops it (`unused config key`)
/// and the override no-ops -> the crate resolves UNPATCHED -> miscompile.
fn write_config(ctx: &Context, paths_lines: &str) -> Result<()> {
    let config_path = generated_config_path(ctx);
    let cargo_dir = config_path.parent().expect("generated config has parent");
    fs::create_dir_all(&cargo_dir).with_context(|| format!("mkdir -p {}", cargo_dir.display()))?;
    let mycorrhiza = ctx.paths.sdk_crates_root.join("mycorrhiza");
    let dotnet_macros = ctx.paths.sdk_crates_root.join("dotnet_macros");
    let sdk_patches = if mycorrhiza.is_dir() && dotnet_macros.is_dir() {
        format!(
            "[patch.crates-io]\nmycorrhiza = {{ path = {:?} }}\ndotnet_macros = {{ path = {:?} }}\n",
            mycorrhiza, dotnet_macros
        )
    } else {
        String::new()
    };
    let config = format!(
        "# GENERATED by cargo dotnet (overlays::apply) — do not hand-edit.\n\
         paths = [\n{paths_lines}]\n\
         [build]\n\
         target = {spec}\n\
         [unstable]\n\
         build-std = [\"core\", \"alloc\", \"std\", \"panic_unwind\"]\n\
         {sdk_patches}",
        spec = toml_path_literal(&ctx.paths.target_spec),
        sdk_patches = sdk_patches,
    );
    fs::write(&config_path, config).with_context(|| format!("write {}", config_path.display()))?;
    Ok(())
}

pub fn generated_config_path(ctx: &Context) -> std::path::PathBuf {
    let key = format!(
        "{:x}",
        Sha256::digest(ctx.crate_dir.to_string_lossy().as_bytes())
    );
    ctx.paths
        .cargo_home
        .join("configs")
        .join(format!("{key}.toml"))
}

pub(crate) fn remove_legacy_generated_config(crate_dir: &Path) -> Result<()> {
    let path = crate_dir.join(".cargo/config.toml");
    if !path.is_file() {
        return Ok(());
    }
    let text = fs::read_to_string(&path)?;
    if text.starts_with("# GENERATED by cargo dotnet (overlays::apply) — do not hand-edit.\n")
        || text.starts_with(
            "# GENERATED by feasibility/cargo-dotnet (apply_overlays) — do not hand-edit.\n",
        )
    {
        fs::remove_file(&path)
            .with_context(|| format!("remove legacy generated config {}", path.display()))?;
    }
    Ok(())
}

/// Regenerate the explicit build-local Cargo config from scratch with the overlay
/// paths-override, preserving the CRITICAL emit order, then warn on a lock mismatch.
///
/// SINGLE-VERSION-PER-NAME RULE (the getrandom multi-major footgun): cargo's `paths`
/// override picks exactly ONE version per crate NAME for the whole graph — with several
/// same-name dirs in `paths` it takes the HIGHEST and warns it "altered the original
/// list of dependencies", which would wrongly link e.g. rand's rand_core (needs
/// getrandom 0.2) against the 0.4 overlay and fail. So for a name with MULTIPLE
/// registry overlays (getrandom 0.2/0.3/0.4) we emit ONLY the dir whose version is
/// LOCKED in THIS project — making it a single-version override (the proven-reliable
/// mio/socket2/tokio shape). That needs the lock FIRST, so we generate it with a
/// paths-free config before building the filtered paths list.
pub fn apply(ctx: &Context) -> Result<()> {
    remove_legacy_generated_config(&ctx.crate_dir)?;
    prepare_private_cargo_auth(ctx)?;
    let reg_path = ctx.paths.overlays_root.join("REGISTRY.toml");
    if !reg_path.is_file() {
        eprintln!(
            "==> no overlay registry at {} (skipping auto-apply)",
            reg_path.display()
        );
        return Ok(());
    }
    let reg_text =
        fs::read_to_string(&reg_path).with_context(|| format!("read {}", reg_path.display()))?;
    let reg: Registry =
        toml::from_str(&reg_text).with_context(|| format!("parse {}", reg_path.display()))?;

    // STEP 1: write a paths-FREE config so the lock can be generated against the dotnet
    // target. (The override doesn't change WHICH versions resolve — only the source dir
    // at compile time — so a paths-free lock pins the same versions the final build
    // uses; it just lets us read them to filter the paths.)
    write_config(ctx, "")?;
    let lock_path = ctx.crate_dir.join("Cargo.lock");
    if !lock_path.is_file() {
        let mut lock_cmd = Command::new(&ctx.cargo);
        lock_cmd.current_dir(&ctx.crate_dir);
        // Pin the toolchain when installed, same as `base_cargo()` — otherwise this
        // bare `cargo` resolves to rustup's default (stable) toolchain, which rejects
        // `-Z` flags. Only matters on a fresh crate with no Cargo.lock yet (the common
        // first-build case), which is why it can go unnoticed.
        if let Some(tc) = &ctx.toolchain {
            lock_cmd.env("RUSTUP_TOOLCHAIN", tc);
        }
        // Lock generation can contact an alternate/private registry.  It must see the
        // copied credentials and must never populate the caller's CARGO_HOME before
        // the ordinary build command takes over.
        lock_cmd.env("CARGO_HOME", &ctx.paths.cargo_home);
        if let Some(config) = ambient_cargo_config(ctx) {
            lock_cmd.arg("--config").arg(config);
        }
        let _ = lock_cmd
            .arg("--config")
            .arg(generated_config_path(ctx))
            .arg("-Zjson-target-spec")
            .arg("generate-lockfile")
            .status();
    }
    let locked: Option<Lock> = if lock_path.is_file() {
        fs::read_to_string(&lock_path)
            .ok()
            .and_then(|t| toml::from_str(&t).ok())
    } else {
        None
    };

    // count overlays per name (to detect multi-version names).
    let mut name_count: HashMap<&str, usize> = HashMap::new();
    for ov in &reg.overlay {
        *name_count.entry(ov.name.as_str()).or_insert(0) += 1;
    }

    // STEP 2: build the paths list. Include an overlay's dir IFF either (a) its name has
    // a single registry overlay (mio/socket2/tokio — always emit; cargo ignores it when
    // the crate isn't in the graph), or (b) its name has MULTIPLE overlays AND this
    // overlay's version is the one LOCKED (so only the matching getrandom major's dir is
    // emitted — single-version-per-name).
    let mut paths_lines = String::new();
    for ov in &reg.overlay {
        let dir = ctx.paths.overlays_root.join(&ov.dir);
        if !dir.is_dir() {
            eprintln!("!! overlay dir missing: {}", dir.display());
            continue;
        }
        let multi = name_count.get(ov.name.as_str()).copied().unwrap_or(1) > 1;
        if multi {
            let locked = locked.as_ref().is_some_and(|l| {
                l.package
                    .iter()
                    .any(|p| p.name == ov.name && p.version == ov.version)
            });
            if !locked {
                continue; // a non-locked major of a multi-version name — skip its dir.
            }
        }
        paths_lines.push_str(&format!("    {},\n", toml_path_literal(&dir)));
    }

    // STEP 3: regenerate the explicit build-local config with the filtered paths.
    write_config(ctx, &paths_lines)?;
    if ctx.flags.verbose {
        eprintln!("==> regenerated build-local Cargo config with dotnet_overlays paths override");
    }

    // Verify each overlay's declared version against the locked version; warn loudly on
    // a REAL mismatch (cargo would silently ignore the override -> miscompile risk).
    if lock_path.is_file() {
        warn_on_lock_mismatch(&lock_path, &reg)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn windows_paths_are_valid_toml_literals() {
        let overlay = Path::new(r"D:\a\rustc_codegen_clr\dotnet_overlays\mio");
        let target = Path::new(r"D:\a\rustc_codegen_clr\x86_64-unknown-dotnet.json");
        let source = format!(
            "paths = [{}]\n[build]\ntarget = {}\n",
            toml_path_literal(overlay),
            toml_path_literal(target)
        );
        let parsed: toml::Value = toml::from_str(&source).expect("Windows paths parse as TOML");
        assert_eq!(parsed["paths"][0].as_str(), overlay.to_str());
        assert_eq!(parsed["build"]["target"].as_str(), target.to_str());
    }
}

/// Layer user/enterprise Cargo source configuration without letting Cargo write registries or
/// caches into the ambient CARGO_HOME. Credentials are copied with their original permissions into
/// the private home; neither their bytes nor tokens are included in receipts or logs.
pub fn prepare_private_cargo_auth(ctx: &Context) -> Result<()> {
    prepare_private_cargo_auth_at(&ctx.paths.cargo_home)
}

/// Copy Cargo's credential file into a cargo-dotnet-owned home without ever rendering its
/// contents. Used by both the build pipeline and metadata discovery, which must resolve the same
/// private sources without falling back to the caller's cache.
pub fn prepare_private_cargo_auth_at(cargo_home: &Path) -> Result<()> {
    fs::create_dir_all(cargo_home)?;
    let Some(ambient) = ambient_cargo_home_for(cargo_home) else {
        return Ok(());
    };
    for name in ["credentials.toml", "credentials"] {
        let source = ambient.join(name);
        if source.is_file() {
            let destination = cargo_home.join(name);
            fs::copy(&source, &destination).with_context(|| {
                format!(
                    "copy Cargo credentials {} -> {}",
                    source.display(),
                    destination.display()
                )
            })?;
            fs::set_permissions(&destination, fs::metadata(&source)?.permissions())?;
        }
    }
    Ok(())
}

pub fn ambient_cargo_config(ctx: &Context) -> Option<std::path::PathBuf> {
    ambient_cargo_config_for(&ctx.paths.cargo_home)
}

/// The caller-owned Cargo config is deliberately passed as an explicit lower-precedence config
/// while the actual cache and credentials live in cargo-dotnet's private home.
pub fn ambient_cargo_config_for(cargo_home: &Path) -> Option<std::path::PathBuf> {
    let home = ambient_cargo_home_for(cargo_home)?;
    [home.join("config.toml"), home.join("config")]
        .into_iter()
        .find(|path| path.is_file())
}

fn ambient_cargo_home_for(cargo_home: &Path) -> Option<std::path::PathBuf> {
    let home = std::env::var_os("CARGO_HOME")
        .map(std::path::PathBuf::from)
        .or_else(|| {
            crate::host::home_dir().map(|home| home.join(".cargo"))
        })?;
    (home != cargo_home).then_some(home)
}

/// Parse Cargo.lock and warn if an overlay's declared version != the locked version
/// (the "overlay silently not applied" footgun). The lock is TOML, so this replaces the
/// bash awk/paste scan with a typed parse.
fn warn_on_lock_mismatch(lock: &Path, reg: &Registry) -> Result<()> {
    let text = fs::read_to_string(lock).with_context(|| format!("read {}", lock.display()))?;
    let parsed: Lock = match toml::from_str(&text) {
        Ok(l) => l,
        Err(_) => return Ok(()), // a malformed/partial lock isn't fatal to the build.
    };
    // Verify the overlays against the lock; warn loudly only on a REAL mismatch.
    // MULTI-VERSION aware: a crate NAME may appear several times in the lock (the three
    // getrandom majors can coexist in one graph) with one overlay per major.
    //   (1) APPLIED   — this overlay's exact (name, version) is locked. (The old code
    //       matched name-only and stopped at the first hit, mis-flagging siblings.)
    //   (2) MISMATCH  — a LOCKED version of an overlaid name is covered by NO overlay
    //       at all (cargo resolves it UNPATCHED -> the footgun). A sibling overlay whose
    //       version simply isn't in THIS graph (e.g. the getrandom 0.2/0.3 overlays when
    //       only 0.4 is locked) is INERT, not a footgun — reported silently.
    // For single-version crates (mio/socket2/tokio) this is behaviour-identical.

    // (1) per-overlay APPLIED (exact name+version locked).
    for ov in &reg.overlay {
        if parsed
            .package
            .iter()
            .any(|p| p.name == ov.name && p.version == ov.version)
        {
            eprintln!("==> overlay APPLIED: {} {} (locked)", ov.name, ov.version);
        }
    }
    // (2) per-overlaid-NAME footgun: a locked version that NO overlay covers.
    let mut names: Vec<&str> = reg.overlay.iter().map(|o| o.name.as_str()).collect();
    names.sort_unstable();
    names.dedup();
    for name in names {
        for pkg in parsed.package.iter().filter(|p| p.name == name) {
            let covered = reg
                .overlay
                .iter()
                .any(|o| o.name == name && o.version == pkg.version);
            if !covered {
                eprintln!(
                    "!! OVERLAY VERSION MISMATCH: {name} is locked at {} but no dotnet_overlays/ dir covers it",
                    pkg.version
                );
                eprintln!(
                    "!! cargo will resolve {name} {} UNPATCHED (footgun: overlay NOT applied).",
                    pkg.version
                );
                eprintln!(
                    "!! Fix: refresh/add a dotnet_overlays/ dir for {name} {} + a REGISTRY.toml entry.",
                    pkg.version
                );
            }
        }
    }
    Ok(())
}
