#!/usr/bin/env bash
# Serialized end-to-end compatibility gate for the ecosystem and managed-library
# cases that exercise the rearchitecture's affected surfaces.
set -u

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
driver="$repo/tools/cargo-dotnet/target/release/cargo-dotnet"
summary="${RCL_MATRIX_SUMMARY:-/tmp/rustc_codegen_clr-e2e-matrix.tsv}"
log_dir="${RCL_MATRIX_LOG_DIR:-/tmp/rustc_codegen_clr-e2e-matrix}"
native_target_root="${RCL_MATRIX_NATIVE_TARGET_ROOT:-/tmp/rustc_codegen_clr-native-matrix}"
read -r -a profiles <<< "${RCL_MATRIX_PROFILES:-release debug}"
case_filter="${RCL_MATRIX_CASES:-}"

if [[ ! -x "$driver" ]]; then
    echo "cargo-dotnet driver is missing; build it with:" >&2
    echo "  cargo build --manifest-path tools/cargo-dotnet/Cargo.toml --release" >&2
    exit 2
fi

# Ordinary Rust ecosystem probes have a stronger oracle than a marker: their
# stdout and exit status must exactly match the same locked crate built natively.
native_diff_cases=(
    soak_ahash soak_aho-corasick soak_anyhow soak_arrayvec soak_base64 soak_bincode
    soak_bitflags soak_blake3 soak_bytes soak_chrono soak_csv soak_fastrand soak_fxhash
    soak_indexmap soak_itertools soak_num_bigint soak_num-rational soak_regex soak_serde_json
    soak_sha2 soak_smallvec soak_strsim soak_time soak_url soak_uuid
    survey_cgmath survey_chacha20 survey_dashmap survey_futures-lite survey_glam
    survey_hashbrown survey_jiff survey_json5 survey_lru survey_nalgebra survey_ndarray
    survey_rayon survey_regex-automata survey_serde_with survey_smol
)

# Managed-only probes cannot be compiled natively. Each must print its exact
# completion marker only after its internal assertions/pass-count checks succeed.
managed_selfcheck_cases=(
    cd_bcl cd_collections cd_decimal cd_span cd_sync cd_idiomatic cd_enumerate cd_json
    cd_delegates cd_async cd_generic cd_fatptr cd_fpfam cd_dynamic_invoke cd_pure
    cd_persisted_async cd_channel cd_tokio cd_static_field_offset cd_subword_atomics
    cd_htmlagility cd_linq_expr cd_efcore cd_linq_groupby cd_pdb cd_pdfsharp
)

# This crate is a cdylib. `cargo dotnet run` cannot execute it; its C# consumer
# is the oracle and must be run explicitly after building the Rust assembly.
managed_host_cases=(cd_export_ergonomics)

diagnostics='(^error(\[|:)|compiler unexpectedly panicked|could not compile item|panicked at|final post-link verification failed|verification failed|unsupported inline assembly|unsupported operation|miscompilation|fatal error|^unhandled exception|^process terminated|warning: allocation requires alignment)'

remove_generated_config() {
    local case_dir="$1"
    local config="$case_dir/.cargo/config.toml"
    local first_line
    [[ -f "$config" ]] || return 0
    IFS= read -r first_line < "$config" || true
    case "$first_line" in
        '# GENERATED by cargo dotnet (overlays::apply) — do not hand-edit.'|'# GENERATED by feasibility/cargo-dotnet (apply_overlays) — do not hand-edit.')
            rm -f "$config"
            ;;
        *)
            echo "refusing to remove unrecognized Cargo config: $config" >&2
            return 1
            ;;
    esac
}

profile_args() {
    case "$1" in
        release) printf '%s\n' --release ;;
        debug) printf '%s\n' --debug ;;
        *) echo "unsupported matrix profile: $1" >&2; return 2 ;;
    esac
}

case_selected() {
    [[ -z "$case_filter" || " $case_filter " == *" $1 "* ]]
}

native_profile_args() {
    [[ "$1" == release ]] && printf '%s\n' --release
    return 0
}

mkdir -p "$log_dir" "$native_target_root" "$(dirname "$summary")"
printf 'kind|profile|case|dotnet_exit|native_exit|stdout_match|diagnostic_hits|marker|required\n' > "$summary"
overall=0
index=0
selected_count=0
for candidate in "${native_diff_cases[@]}" "${managed_selfcheck_cases[@]}" "${managed_host_cases[@]}"; do
    case_selected "$candidate" && selected_count=$((selected_count + 1))
done
total=$((selected_count * ${#profiles[@]}))

run_native_diff() {
    local case_name="$1" profile="$2" clean_flag="$3"
    local case_dir="$repo/cargo_tests/$case_name"
    local prefix="$log_dir/$profile-$case_name"
    local dotnet_exit native_exit hits stdout_match marker dotnet_profile native_profile

    remove_generated_config "$case_dir" || return 1
    dotnet_profile="$(profile_args "$profile")" || return 1
    native_profile="$(native_profile_args "$profile")"

    env -u RUSTFLAGS -u CARGO_ENCODED_RUSTFLAGS -u CARGO_BUILD_TARGET \
        -u C_MODE -u JS_MODE -u ILASM_PATH -u DOTNET_VERSION \
        CARGO_TARGET_DIR="$native_target_root/$case_name/$profile" \
        cargo +nightly-2026-06-17 run --manifest-path "$case_dir/Cargo.toml" \
        $native_profile --locked --quiet > "$prefix.native.stdout" 2> "$prefix.native.stderr"
    native_exit=$?

    RCL_ICE_LOG=1 CARGO_DOTNET_BACKEND=native \
        "$driver" dotnet run "$case_dir" "$dotnet_profile" $clean_flag --locked \
        > "$prefix.dotnet.stdout" 2> "$prefix.dotnet.stderr"
    dotnet_exit=$?
    remove_generated_config "$case_dir" || return 1

    tr -d '\r' < "$prefix.native.stdout" > "$prefix.native.normalized"
    tr -d '\r' < "$prefix.dotnet.stdout" > "$prefix.dotnet.normalized"
    if cmp -s "$prefix.native.normalized" "$prefix.dotnet.normalized"; then
        stdout_match=yes
    else
        stdout_match=no
        diff -u "$prefix.native.normalized" "$prefix.dotnet.normalized" > "$prefix.stdout.diff" || true
    fi
    hits="$(rg -n -i "$diagnostics" "$prefix.dotnet.stdout" "$prefix.dotnet.stderr" 2>/dev/null | wc -l | tr -d ' ')"
    if rg -q "== $case_name done ==" "$prefix.dotnet.stdout"; then marker=yes; else marker=no; fi
    printf 'native_diff|%s|%s|%d|%d|%s|%s|%s|no\n' \
        "$profile" "$case_name" "$dotnet_exit" "$native_exit" "$stdout_match" "$hits" "$marker" >> "$summary"
    ((dotnet_exit == 0 && native_exit == 0 && hits == 0)) && [[ "$stdout_match" == yes ]]
}

run_managed_selfcheck() {
    local case_name="$1" profile="$2" clean_flag="$3"
    local case_dir="$repo/cargo_tests/$case_name"
    local prefix="$log_dir/$profile-$case_name"
    local dotnet_exit hits marker dotnet_profile
    dotnet_profile="$(profile_args "$profile")" || return 1

    RCL_ICE_LOG=1 CARGO_DOTNET_BACKEND=native \
        "$driver" dotnet run "$case_dir" "$dotnet_profile" $clean_flag --locked \
        > "$prefix.dotnet.stdout" 2> "$prefix.dotnet.stderr"
    dotnet_exit=$?
    hits="$(rg -n -i "$diagnostics" "$prefix.dotnet.stdout" "$prefix.dotnet.stderr" 2>/dev/null | wc -l | tr -d ' ')"
    if rg -q "== $case_name done ==" "$prefix.dotnet.stdout"; then marker=yes; else marker=no; fi
    printf 'managed_selfcheck|%s|%s|%d|na|na|%s|%s|yes\n' \
        "$profile" "$case_name" "$dotnet_exit" "$hits" "$marker" >> "$summary"
    ((dotnet_exit == 0 && hits == 0)) && [[ "$marker" == yes ]]
}

run_managed_host() {
    local case_name="$1" profile="$2" clean_flag="$3"
    local case_dir="$repo/cargo_tests/$case_name"
    local prefix="$log_dir/$profile-$case_name"
    local dotnet_exit hits marker dotnet_profile
    dotnet_profile="$(profile_args "$profile")" || return 1

    RCL_ICE_LOG=1 CARGO_DOTNET_BACKEND=native \
        "$driver" dotnet build "$case_dir" "$dotnet_profile" $clean_flag --locked \
        > "$prefix.build.stdout" 2> "$prefix.build.stderr"
    dotnet_exit=$?
    if ((dotnet_exit == 0)); then
        dotnet run --project "$case_dir/csharp/cd_export_ergonomics_cs.csproj" \
            --property:RustProfile="$profile" > "$prefix.dotnet.stdout" 2> "$prefix.dotnet.stderr"
        dotnet_exit=$?
    else
        : > "$prefix.dotnet.stdout"
        : > "$prefix.dotnet.stderr"
    fi
    hits="$(rg -n -i "$diagnostics" "$prefix.build.stdout" "$prefix.build.stderr" \
        "$prefix.dotnet.stdout" "$prefix.dotnet.stderr" 2>/dev/null | wc -l | tr -d ' ')"
    if rg -q "== $case_name done ==" "$prefix.dotnet.stdout"; then marker=yes; else marker=no; fi
    printf 'managed_host|%s|%s|%d|na|na|%s|%s|yes\n' \
        "$profile" "$case_name" "$dotnet_exit" "$hits" "$marker" >> "$summary"
    ((dotnet_exit == 0 && hits == 0)) && [[ "$marker" == yes ]]
}

for kind in native_diff managed_selfcheck managed_host; do
    case "$kind" in
        native_diff) cases=("${native_diff_cases[@]}") ;;
        managed_selfcheck) cases=("${managed_selfcheck_cases[@]}") ;;
        managed_host) cases=("${managed_host_cases[@]}") ;;
    esac
    for case_name in "${cases[@]}"; do
        case_selected "$case_name" || continue
        first_profile=yes
        for profile in "${profiles[@]}"; do
            index=$((index + 1))
            clean_flag=''
            [[ "$first_profile" == yes ]] && clean_flag=--clean
            printf '[%d/%d] START %s %s (%s)\n' "$index" "$total" "$profile" "$case_name" "$kind"
            if "run_$kind" "$case_name" "$profile" "$clean_flag"; then
                result=PASS
            else
                result=FAIL
                overall=1
            fi
            printf '[%d/%d] END %s %s %s\n' "$index" "$total" "$profile" "$case_name" "$result"
            first_profile=no
        done
        if [[ "${RCL_MATRIX_KEEP_TARGETS:-0}" != 1 ]]; then
            rm -rf "$repo/cargo_tests/$case_name/target"
        fi
    done
done

echo "summary: $summary"
echo "logs: $log_dir"
RCL_MATRIX_COMMAND="RCL_MATRIX_PROFILES=${RCL_MATRIX_PROFILES:-release debug} RCL_MATRIX_CASES=${RCL_MATRIX_CASES:-<all>} feasibility/e2e_matrix.sh" \
    "$repo/feasibility/write_acceptance_receipt.sh" \
    "$summary" "${summary%.*}.receipt.json" "$log_dir" || overall=1
exit "$overall"
