#!/usr/bin/env bash
# Product-shaped proof that add-nuget preserves byte[] + interface calls and the generated
# bindings round-trip two distinct payloads through a real NATS server in debug and release.
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
driver="$repo/tools/cargo-dotnet/target/release/cargo-dotnet"
dotnet_version="${DOTNET_VERSION:-10}"
work="${RCL_NATS_WORK_DIR:-$(mktemp -d)}"
logs="${RCL_NATS_LOG_DIR:-$work/logs}"
generated="$work/generated"
container=""

cleanup() {
    if [[ -n "$container" ]]; then
        docker rm -f "$container" >/dev/null 2>&1 || true
    fi
    if [[ -z "${RCL_NATS_WORK_DIR:-}" && "${RCL_NATS_KEEP_WORK:-0}" != 1 ]]; then
        rm -rf "$work"
    fi
}
trap cleanup EXIT

mkdir -p "$generated/src" "$logs"
cargo build --manifest-path "$repo/tools/cargo-dotnet/Cargo.toml" --release \
    > "$logs/driver-build.log" 2>&1
[[ -x "$driver" ]]
cargo build --release --workspace > "$logs/backend-build.log" 2>&1
printf '[package]\nname = "generated_nats_probe"\nversion = "0.0.0"\nedition = "2024"\n\n[workspace]\n' \
    > "$generated/Cargo.toml"
printf '#![allow(dead_code)]\n' > "$generated/src/lib.rs"

"$driver" add-nuget NATS.Client 1.1.8 "$generated" --force --dotnet "$dotnet_version" \
    > "$logs/generate.log" 2>&1
bindings="$generated/src/nuget/nats_client.rs"
rg -q 'fn publish\(self, a1: System::String, a2: mycorrhiza::intrinsics::RustcCLRInteropManagedArray<u8, 1>\)' "$bindings"
rg -q 'fn get_data\(self\) -> mycorrhiza::intrinsics::RustcCLRInteropManagedArray<u8, 1>' "$bindings"
rg -q 'self\.virt2::<"Publish"' "$bindings"
[[ ! -d "$repo/cargo_tests/cd_nats/csharp_helper" ]]

nats_url="${NATS_URL:-}"
if [[ -z "$nats_url" ]]; then
    command -v docker >/dev/null 2>&1 || {
        echo "nats managed-array acceptance requires NATS_URL or Docker" >&2
        exit 2
    }
    container="rcl-nats-array-$$"
    docker run --rm --name "$container" -d -p '127.0.0.1::4222' \
        "${RCL_NATS_IMAGE:-nats:2.11-alpine}" > "$logs/container-id.txt"
    host_port="$(docker port "$container" '4222/tcp' | awk -F: 'NR == 1 { print $NF }')"
    [[ "$host_port" =~ ^[0-9]+$ ]]
    nats_url="nats://127.0.0.1:$host_port"
    ready=0
    for _ in 1 2 3 4 5 6 7 8 9 10; do
        if nc -z 127.0.0.1 "$host_port"; then
            ready=1
            break
        fi
        sleep 1
    done
    [[ "$ready" == 1 ]] || {
        docker logs "$container" >&2 || true
        echo "nats managed-array acceptance: server did not become ready" >&2
        exit 1
    }
fi

for profile in release debug; do
    NATS_URL="$nats_url" CARGO_DOTNET_BACKEND=native \
        "$driver" run "$repo/cargo_tests/cd_nats" "--$profile" --dotnet "$dotnet_version" \
        > "$logs/$profile.log" 2>&1
    rg -q '^== cd_nats done ==$' "$logs/$profile.log"
    [[ "$(rg -c '^2$' "$logs/$profile.log")" -ge 2 ]]
done

echo "== nats_managed_array_acceptance done: generated byte[] bindings, no C# shim, real debug+release roundtrip =="
echo "logs: $logs"
