// Generated by `cargo dotnet add-nuget` — do not hand-edit (re-run add-nuget instead).
#[allow(unused_imports)]
use mycorrhiza::bindings::System;

pub trait UpcastTo<T> { fn upcast(self) -> T; }
pub mod HtmlAgilityPack{
pub type Crc32 =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.Crc32">;
use super::*;
impl UpcastTo<System::Object> for Crc32 {
 fn upcast(self)->System::Object{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::Object,Crc32>(self)
}} 
pub trait Crc32_Methods {
    fn crc32_string(a1: System::String) -> u32;
    fn new() -> Self;
}
impl Crc32_Methods for Crc32 {
    fn crc32_string(a1: System::String) -> u32 { Self::static1::<"CRC32String", System::String, u32>(a1) }
    fn new() -> Self { Self::ctor0() }
}
pub type HtmlAttribute =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.HtmlAttribute">;
use super::*;
impl UpcastTo<System::Object> for HtmlAttribute {
 fn upcast(self)->System::Object{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::Object,HtmlAttribute>(self)
}} 
pub trait HtmlAttribute_Methods {
    fn get_line(self) -> i32;
    fn get_line_position(self) -> i32;
    fn get_value_start_index(self) -> i32;
    fn get_value_length(self) -> i32;
    fn get_use_original_name(self) -> bool;
    fn set_use_original_name(self, a1: bool);
    fn get_name(self) -> System::String;
    fn set_name(self, a1: System::String);
    fn get_original_name(self) -> System::String;
    fn get_owner_document(self) -> HtmlAgilityPack::HtmlDocument;
    fn get_owner_node(self) -> HtmlAgilityPack::HtmlNode;
    fn get_stream_position(self) -> i32;
    fn get_value(self) -> System::String;
    fn set_value(self, a1: System::String);
    fn get_de_entitize_value(self) -> System::String;
    fn get_xpath(self) -> System::String;
    fn compare_to(self, a1: System::Object) -> i32;
    fn clone(self) -> HtmlAgilityPack::HtmlAttribute;
    fn remove(self);
}
impl HtmlAttribute_Methods for HtmlAttribute {
    fn get_line(self) -> i32 { self.instance0::<"get_Line", i32>() }
    fn get_line_position(self) -> i32 { self.instance0::<"get_LinePosition", i32>() }
    fn get_value_start_index(self) -> i32 { self.instance0::<"get_ValueStartIndex", i32>() }
    fn get_value_length(self) -> i32 { self.instance0::<"get_ValueLength", i32>() }
    fn get_use_original_name(self) -> bool { self.instance0::<"get_UseOriginalName", bool>() }
    fn set_use_original_name(self, a1: bool) { self.instance1::<"set_UseOriginalName", bool, ()>(a1) }
    fn get_name(self) -> System::String { self.instance0::<"get_Name", System::String>() }
    fn set_name(self, a1: System::String) { self.instance1::<"set_Name", System::String, ()>(a1) }
    fn get_original_name(self) -> System::String { self.instance0::<"get_OriginalName", System::String>() }
    fn get_owner_document(self) -> HtmlAgilityPack::HtmlDocument { self.instance0::<"get_OwnerDocument", HtmlAgilityPack::HtmlDocument>() }
    fn get_owner_node(self) -> HtmlAgilityPack::HtmlNode { self.instance0::<"get_OwnerNode", HtmlAgilityPack::HtmlNode>() }
    fn get_stream_position(self) -> i32 { self.instance0::<"get_StreamPosition", i32>() }
    fn get_value(self) -> System::String { self.instance0::<"get_Value", System::String>() }
    fn set_value(self, a1: System::String) { self.instance1::<"set_Value", System::String, ()>(a1) }
    fn get_de_entitize_value(self) -> System::String { self.instance0::<"get_DeEntitizeValue", System::String>() }
    fn get_xpath(self) -> System::String { self.instance0::<"get_XPath", System::String>() }
    fn compare_to(self, a1: System::Object) -> i32 { self.instance1::<"CompareTo", System::Object, i32>(a1) }
    fn clone(self) -> HtmlAgilityPack::HtmlAttribute { self.instance0::<"Clone", HtmlAgilityPack::HtmlAttribute>() }
    fn remove(self) { self.instance0::<"Remove", ()>() }
}
pub type HtmlAttributeCollection =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.HtmlAttributeCollection">;
use super::*;
impl UpcastTo<System::Object> for HtmlAttributeCollection {
 fn upcast(self)->System::Object{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::Object,HtmlAttributeCollection>(self)
}} 
pub trait HtmlAttributeCollection_Methods {
    fn get_count(self) -> i32;
    fn get_is_read_only(self) -> bool;
    fn get_item(self, a1: i32) -> HtmlAgilityPack::HtmlAttribute;
    fn set_item(self, a1: i32, a2: HtmlAgilityPack::HtmlAttribute);
    fn add(self, a1: System::String, a2: System::String);
    fn contains(self, a1: HtmlAgilityPack::HtmlAttribute) -> bool;
    fn index_of(self, a1: HtmlAgilityPack::HtmlAttribute) -> i32;
    fn insert(self, a1: i32, a2: HtmlAgilityPack::HtmlAttribute);
    fn remove_at(self, a1: i32);
    fn append(self, a1: HtmlAgilityPack::HtmlAttribute) -> HtmlAgilityPack::HtmlAttribute;
    fn prepend(self, a1: HtmlAgilityPack::HtmlAttribute) -> HtmlAgilityPack::HtmlAttribute;
    fn remove(self, a1: HtmlAgilityPack::HtmlAttribute);
    fn remove_all(self);
}
impl HtmlAttributeCollection_Methods for HtmlAttributeCollection {
    fn get_count(self) -> i32 { self.virt0::<"get_Count", i32>() }
    fn get_is_read_only(self) -> bool { self.virt0::<"get_IsReadOnly", bool>() }
    fn get_item(self, a1: i32) -> HtmlAgilityPack::HtmlAttribute { self.instance1::<"get_Item", i32, HtmlAgilityPack::HtmlAttribute>(a1) }
    fn set_item(self, a1: i32, a2: HtmlAgilityPack::HtmlAttribute) { self.instance2::<"set_Item", i32, HtmlAgilityPack::HtmlAttribute, ()>(a1, a2) }
    fn add(self, a1: System::String, a2: System::String) { self.instance2::<"Add", System::String, System::String, ()>(a1, a2) }
    fn contains(self, a1: HtmlAgilityPack::HtmlAttribute) -> bool { self.instance1::<"Contains", HtmlAgilityPack::HtmlAttribute, bool>(a1) }
    fn index_of(self, a1: HtmlAgilityPack::HtmlAttribute) -> i32 { self.instance1::<"IndexOf", HtmlAgilityPack::HtmlAttribute, i32>(a1) }
    fn insert(self, a1: i32, a2: HtmlAgilityPack::HtmlAttribute) { self.instance2::<"Insert", i32, HtmlAgilityPack::HtmlAttribute, ()>(a1, a2) }
    fn remove_at(self, a1: i32) { self.instance1::<"RemoveAt", i32, ()>(a1) }
    fn append(self, a1: HtmlAgilityPack::HtmlAttribute) -> HtmlAgilityPack::HtmlAttribute { self.instance1::<"Append", HtmlAgilityPack::HtmlAttribute, HtmlAgilityPack::HtmlAttribute>(a1) }
    fn prepend(self, a1: HtmlAgilityPack::HtmlAttribute) -> HtmlAgilityPack::HtmlAttribute { self.instance1::<"Prepend", HtmlAgilityPack::HtmlAttribute, HtmlAgilityPack::HtmlAttribute>(a1) }
    fn remove(self, a1: HtmlAgilityPack::HtmlAttribute) { self.instance1::<"Remove", HtmlAgilityPack::HtmlAttribute, ()>(a1) }
    fn remove_all(self) { self.instance0::<"RemoveAll", ()>() }
}
pub type HtmlCommentNode =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.HtmlCommentNode">;
use super::*;
impl UpcastTo<HtmlAgilityPack::HtmlNode> for HtmlCommentNode {
 fn upcast(self)->HtmlAgilityPack::HtmlNode{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<HtmlAgilityPack::HtmlNode,HtmlCommentNode>(self)
}} 
pub trait HtmlCommentNode_Methods {
    fn get_comment(self) -> System::String;
    fn set_comment(self, a1: System::String);
    fn get_inner_html(self) -> System::String;
    fn set_inner_html(self, a1: System::String);
    fn get_outer_html(self) -> System::String;
}
impl HtmlCommentNode_Methods for HtmlCommentNode {
    fn get_comment(self) -> System::String { self.instance0::<"get_Comment", System::String>() }
    fn set_comment(self, a1: System::String) { self.instance1::<"set_Comment", System::String, ()>(a1) }
    fn get_inner_html(self) -> System::String { self.virt0::<"get_InnerHtml", System::String>() }
    fn set_inner_html(self, a1: System::String) { self.instance1::<"set_InnerHtml", System::String, ()>(a1) }
    fn get_outer_html(self) -> System::String { self.virt0::<"get_OuterHtml", System::String>() }
}
pub type HtmlDocument =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.HtmlDocument">;
use super::*;
impl UpcastTo<System::Object> for HtmlDocument {
 fn upcast(self)->System::Object{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::Object,HtmlDocument>(self)
}} 
pub trait HtmlDocument_Methods {
    fn get_disable_behavior_tag_p() -> bool;
    fn set_disable_behavior_tag_p(a1: bool);
    fn get_parsed_text(self) -> System::String;
    fn get_max_depth_level() -> i32;
    fn set_max_depth_level(a1: i32);
    fn get_check_sum(self) -> i32;
    fn get_declared_encoding(self) -> System::Text::Encoding;
    fn get_document_node(self) -> HtmlAgilityPack::HtmlNode;
    fn get_encoding(self) -> System::Text::Encoding;
    fn get_remainder(self) -> System::String;
    fn get_remainder_offset(self) -> i32;
    fn get_stream_encoding(self) -> System::Text::Encoding;
    fn get_xml_name(a1: System::String) -> System::String;
    fn use_attribute_original_name(self, a1: System::String);
    fn html_encode(a1: System::String) -> System::String;
    fn is_white_space(a1: i32) -> bool;
    fn create_attribute(self, a1: System::String) -> HtmlAgilityPack::HtmlAttribute;
    fn create_comment(self) -> HtmlAgilityPack::HtmlCommentNode;
    fn create_element(self, a1: System::String) -> HtmlAgilityPack::HtmlNode;
    fn create_text_node(self) -> HtmlAgilityPack::HtmlTextNode;
    fn detect_encoding(self, a1: System::IO::Stream) -> System::Text::Encoding;
    fn detect_encoding_html(self, a1: System::String) -> System::Text::Encoding;
    fn get_elementby_id(self, a1: System::String) -> HtmlAgilityPack::HtmlNode;
    fn load(self, a1: System::IO::Stream);
    fn load_html(self, a1: System::String);
    fn save(self, a1: System::IO::Stream);
    fn detect_encoding_and_load(self, a1: System::String);
    fn new() -> Self;
}
impl HtmlDocument_Methods for HtmlDocument {
    fn get_disable_behavior_tag_p() -> bool { Self::static0::<"get_DisableBehaviorTagP", bool>() }
    fn set_disable_behavior_tag_p(a1: bool) { Self::static1::<"set_DisableBehaviorTagP", bool, ()>(a1) }
    fn get_parsed_text(self) -> System::String { self.instance0::<"get_ParsedText", System::String>() }
    fn get_max_depth_level() -> i32 { Self::static0::<"get_MaxDepthLevel", i32>() }
    fn set_max_depth_level(a1: i32) { Self::static1::<"set_MaxDepthLevel", i32, ()>(a1) }
    fn get_check_sum(self) -> i32 { self.instance0::<"get_CheckSum", i32>() }
    fn get_declared_encoding(self) -> System::Text::Encoding { self.instance0::<"get_DeclaredEncoding", System::Text::Encoding>() }
    fn get_document_node(self) -> HtmlAgilityPack::HtmlNode { self.instance0::<"get_DocumentNode", HtmlAgilityPack::HtmlNode>() }
    fn get_encoding(self) -> System::Text::Encoding { self.instance0::<"get_Encoding", System::Text::Encoding>() }
    fn get_remainder(self) -> System::String { self.instance0::<"get_Remainder", System::String>() }
    fn get_remainder_offset(self) -> i32 { self.instance0::<"get_RemainderOffset", i32>() }
    fn get_stream_encoding(self) -> System::Text::Encoding { self.instance0::<"get_StreamEncoding", System::Text::Encoding>() }
    fn get_xml_name(a1: System::String) -> System::String { Self::static1::<"GetXmlName", System::String, System::String>(a1) }
    fn use_attribute_original_name(self, a1: System::String) { self.instance1::<"UseAttributeOriginalName", System::String, ()>(a1) }
    fn html_encode(a1: System::String) -> System::String { Self::static1::<"HtmlEncode", System::String, System::String>(a1) }
    fn is_white_space(a1: i32) -> bool { Self::static1::<"IsWhiteSpace", i32, bool>(a1) }
    fn create_attribute(self, a1: System::String) -> HtmlAgilityPack::HtmlAttribute { self.instance1::<"CreateAttribute", System::String, HtmlAgilityPack::HtmlAttribute>(a1) }
    fn create_comment(self) -> HtmlAgilityPack::HtmlCommentNode { self.instance0::<"CreateComment", HtmlAgilityPack::HtmlCommentNode>() }
    fn create_element(self, a1: System::String) -> HtmlAgilityPack::HtmlNode { self.instance1::<"CreateElement", System::String, HtmlAgilityPack::HtmlNode>(a1) }
    fn create_text_node(self) -> HtmlAgilityPack::HtmlTextNode { self.instance0::<"CreateTextNode", HtmlAgilityPack::HtmlTextNode>() }
    fn detect_encoding(self, a1: System::IO::Stream) -> System::Text::Encoding { self.instance1::<"DetectEncoding", System::IO::Stream, System::Text::Encoding>(a1) }
    fn detect_encoding_html(self, a1: System::String) -> System::Text::Encoding { self.instance1::<"DetectEncodingHtml", System::String, System::Text::Encoding>(a1) }
    fn get_elementby_id(self, a1: System::String) -> HtmlAgilityPack::HtmlNode { self.instance1::<"GetElementbyId", System::String, HtmlAgilityPack::HtmlNode>(a1) }
    fn load(self, a1: System::IO::Stream) { self.instance1::<"Load", System::IO::Stream, ()>(a1) }
    fn load_html(self, a1: System::String) { self.instance1::<"LoadHtml", System::String, ()>(a1) }
    fn save(self, a1: System::IO::Stream) { self.instance1::<"Save", System::IO::Stream, ()>(a1) }
    fn detect_encoding_and_load(self, a1: System::String) { self.instance1::<"DetectEncodingAndLoad", System::String, ()>(a1) }
    fn new() -> Self { Self::ctor0() }
}
pub type HtmlEntity =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.HtmlEntity">;
use super::*;
impl UpcastTo<System::Object> for HtmlEntity {
 fn upcast(self)->System::Object{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::Object,HtmlEntity>(self)
}} 
pub trait HtmlEntity_Methods {
    fn get_use_web_utility() -> bool;
    fn set_use_web_utility(a1: bool);
    fn de_entitize(a1: System::String) -> System::String;
    fn entitize(a1: HtmlAgilityPack::HtmlNode) -> HtmlAgilityPack::HtmlNode;
}
impl HtmlEntity_Methods for HtmlEntity {
    fn get_use_web_utility() -> bool { Self::static0::<"get_UseWebUtility", bool>() }
    fn set_use_web_utility(a1: bool) { Self::static1::<"set_UseWebUtility", bool, ()>(a1) }
    fn de_entitize(a1: System::String) -> System::String { Self::static1::<"DeEntitize", System::String, System::String>(a1) }
    fn entitize(a1: HtmlAgilityPack::HtmlNode) -> HtmlAgilityPack::HtmlNode { Self::static1::<"Entitize", HtmlAgilityPack::HtmlNode, HtmlAgilityPack::HtmlNode>(a1) }
}
pub type HtmlNode =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.HtmlNode">;
use super::*;
impl UpcastTo<System::Object> for HtmlNode {
 fn upcast(self)->System::Object{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::Object,HtmlNode>(self)
}} 
pub trait HtmlNode_Methods {
    fn get_attributes(self) -> HtmlAgilityPack::HtmlAttributeCollection;
    fn get_child_nodes(self) -> HtmlAgilityPack::HtmlNodeCollection;
    fn get_closed(self) -> bool;
    fn get_closing_attributes(self) -> HtmlAgilityPack::HtmlAttributeCollection;
    fn get_end_node(self) -> HtmlAgilityPack::HtmlNode;
    fn get_first_child(self) -> HtmlAgilityPack::HtmlNode;
    fn get_has_attributes(self) -> bool;
    fn get_has_child_nodes(self) -> bool;
    fn get_has_closing_attributes(self) -> bool;
    fn get_id(self) -> System::String;
    fn set_id(self, a1: System::String);
    fn get_inner_html(self) -> System::String;
    fn set_inner_html(self, a1: System::String);
    fn get_inner_text(self) -> System::String;
    fn get_direct_inner_text(self) -> System::String;
    fn get_last_child(self) -> HtmlAgilityPack::HtmlNode;
    fn get_line(self) -> i32;
    fn get_line_position(self) -> i32;
    fn get_inner_start_index(self) -> i32;
    fn get_outer_start_index(self) -> i32;
    fn get_inner_length(self) -> i32;
    fn get_outer_length(self) -> i32;
    fn get_name(self) -> System::String;
    fn set_name(self, a1: System::String);
    fn get_next_sibling(self) -> HtmlAgilityPack::HtmlNode;
    fn get_original_name(self) -> System::String;
    fn get_outer_html(self) -> System::String;
    fn get_owner_document(self) -> HtmlAgilityPack::HtmlDocument;
    fn get_parent_node(self) -> HtmlAgilityPack::HtmlNode;
    fn get_previous_sibling(self) -> HtmlAgilityPack::HtmlNode;
    fn get_stream_position(self) -> i32;
    fn get_xpath(self) -> System::String;
    fn get_depth(self) -> i32;
    fn set_depth(self, a1: i32);
    fn can_overlap_element(a1: System::String) -> bool;
    fn create_node(a1: System::String) -> HtmlAgilityPack::HtmlNode;
    fn is_cdata_element(a1: System::String) -> bool;
    fn is_closed_element(a1: System::String) -> bool;
    fn is_empty_element(a1: System::String) -> bool;
    fn is_overlapped_closing_element(a1: System::String) -> bool;
    fn append_child(self, a1: HtmlAgilityPack::HtmlNode) -> HtmlAgilityPack::HtmlNode;
    fn set_child_nodes_id(self, a1: HtmlAgilityPack::HtmlNode);
    fn append_children(self, a1: HtmlAgilityPack::HtmlNodeCollection);
    fn clone(self) -> HtmlAgilityPack::HtmlNode;
    fn clone_node(self, a1: System::String) -> HtmlAgilityPack::HtmlNode;
    fn copy_from(self, a1: HtmlAgilityPack::HtmlNode);
    fn element(self, a1: System::String) -> HtmlAgilityPack::HtmlNode;
    fn get_data_attribute(self, a1: System::String) -> HtmlAgilityPack::HtmlAttribute;
    fn get_attribute_value(self, a1: System::String, a2: System::String) -> System::String;
    fn insert_after(self, a1: HtmlAgilityPack::HtmlNode, a2: HtmlAgilityPack::HtmlNode) -> HtmlAgilityPack::HtmlNode;
    fn insert_before(self, a1: HtmlAgilityPack::HtmlNode, a2: HtmlAgilityPack::HtmlNode) -> HtmlAgilityPack::HtmlNode;
    fn prepend_child(self, a1: HtmlAgilityPack::HtmlNode) -> HtmlAgilityPack::HtmlNode;
    fn prepend_children(self, a1: HtmlAgilityPack::HtmlNodeCollection);
    fn remove(self);
    fn remove_all(self);
    fn remove_all_children(self);
    fn remove_all_idfor_node(self, a1: HtmlAgilityPack::HtmlNode);
    fn move_child(self, a1: HtmlAgilityPack::HtmlNode);
    fn move_children(self, a1: HtmlAgilityPack::HtmlNodeCollection);
    fn remove_children(self, a1: HtmlAgilityPack::HtmlNodeCollection);
    fn remove_child(self, a1: HtmlAgilityPack::HtmlNode) -> HtmlAgilityPack::HtmlNode;
    fn replace_child(self, a1: HtmlAgilityPack::HtmlNode, a2: HtmlAgilityPack::HtmlNode) -> HtmlAgilityPack::HtmlNode;
    fn set_attribute_value(self, a1: System::String, a2: System::String) -> HtmlAgilityPack::HtmlAttribute;
    fn write_content_to(self, a1: System::IO::TextWriter, a2: i32);
    fn write_to(self, a1: System::IO::TextWriter, a2: i32);
    fn set_parent(self, a1: HtmlAgilityPack::HtmlNode);
    fn add_class(self, a1: System::String);
    fn remove_class(self);
    fn replace_class(self, a1: System::String, a2: System::String);
    fn has_class(self, a1: System::String) -> bool;
    fn get_encapsulated_data(self, a1: System::Type, a2: HtmlAgilityPack::HtmlDocument) -> System::Object;
    fn select_nodes(self, a1: System::String) -> HtmlAgilityPack::HtmlNodeCollection;
    fn select_single_node(self, a1: System::String) -> HtmlAgilityPack::HtmlNode;
}
impl HtmlNode_Methods for HtmlNode {
    fn get_attributes(self) -> HtmlAgilityPack::HtmlAttributeCollection { self.instance0::<"get_Attributes", HtmlAgilityPack::HtmlAttributeCollection>() }
    fn get_child_nodes(self) -> HtmlAgilityPack::HtmlNodeCollection { self.instance0::<"get_ChildNodes", HtmlAgilityPack::HtmlNodeCollection>() }
    fn get_closed(self) -> bool { self.instance0::<"get_Closed", bool>() }
    fn get_closing_attributes(self) -> HtmlAgilityPack::HtmlAttributeCollection { self.instance0::<"get_ClosingAttributes", HtmlAgilityPack::HtmlAttributeCollection>() }
    fn get_end_node(self) -> HtmlAgilityPack::HtmlNode { self.instance0::<"get_EndNode", HtmlAgilityPack::HtmlNode>() }
    fn get_first_child(self) -> HtmlAgilityPack::HtmlNode { self.instance0::<"get_FirstChild", HtmlAgilityPack::HtmlNode>() }
    fn get_has_attributes(self) -> bool { self.instance0::<"get_HasAttributes", bool>() }
    fn get_has_child_nodes(self) -> bool { self.instance0::<"get_HasChildNodes", bool>() }
    fn get_has_closing_attributes(self) -> bool { self.instance0::<"get_HasClosingAttributes", bool>() }
    fn get_id(self) -> System::String { self.instance0::<"get_Id", System::String>() }
    fn set_id(self, a1: System::String) { self.instance1::<"set_Id", System::String, ()>(a1) }
    fn get_inner_html(self) -> System::String { self.virt0::<"get_InnerHtml", System::String>() }
    fn set_inner_html(self, a1: System::String) { self.instance1::<"set_InnerHtml", System::String, ()>(a1) }
    fn get_inner_text(self) -> System::String { self.virt0::<"get_InnerText", System::String>() }
    fn get_direct_inner_text(self) -> System::String { self.virt0::<"GetDirectInnerText", System::String>() }
    fn get_last_child(self) -> HtmlAgilityPack::HtmlNode { self.instance0::<"get_LastChild", HtmlAgilityPack::HtmlNode>() }
    fn get_line(self) -> i32 { self.instance0::<"get_Line", i32>() }
    fn get_line_position(self) -> i32 { self.instance0::<"get_LinePosition", i32>() }
    fn get_inner_start_index(self) -> i32 { self.instance0::<"get_InnerStartIndex", i32>() }
    fn get_outer_start_index(self) -> i32 { self.instance0::<"get_OuterStartIndex", i32>() }
    fn get_inner_length(self) -> i32 { self.instance0::<"get_InnerLength", i32>() }
    fn get_outer_length(self) -> i32 { self.instance0::<"get_OuterLength", i32>() }
    fn get_name(self) -> System::String { self.instance0::<"get_Name", System::String>() }
    fn set_name(self, a1: System::String) { self.instance1::<"set_Name", System::String, ()>(a1) }
    fn get_next_sibling(self) -> HtmlAgilityPack::HtmlNode { self.instance0::<"get_NextSibling", HtmlAgilityPack::HtmlNode>() }
    fn get_original_name(self) -> System::String { self.instance0::<"get_OriginalName", System::String>() }
    fn get_outer_html(self) -> System::String { self.virt0::<"get_OuterHtml", System::String>() }
    fn get_owner_document(self) -> HtmlAgilityPack::HtmlDocument { self.instance0::<"get_OwnerDocument", HtmlAgilityPack::HtmlDocument>() }
    fn get_parent_node(self) -> HtmlAgilityPack::HtmlNode { self.instance0::<"get_ParentNode", HtmlAgilityPack::HtmlNode>() }
    fn get_previous_sibling(self) -> HtmlAgilityPack::HtmlNode { self.instance0::<"get_PreviousSibling", HtmlAgilityPack::HtmlNode>() }
    fn get_stream_position(self) -> i32 { self.instance0::<"get_StreamPosition", i32>() }
    fn get_xpath(self) -> System::String { self.instance0::<"get_XPath", System::String>() }
    fn get_depth(self) -> i32 { self.instance0::<"get_Depth", i32>() }
    fn set_depth(self, a1: i32) { self.instance1::<"set_Depth", i32, ()>(a1) }
    fn can_overlap_element(a1: System::String) -> bool { Self::static1::<"CanOverlapElement", System::String, bool>(a1) }
    fn create_node(a1: System::String) -> HtmlAgilityPack::HtmlNode { Self::static1::<"CreateNode", System::String, HtmlAgilityPack::HtmlNode>(a1) }
    fn is_cdata_element(a1: System::String) -> bool { Self::static1::<"IsCDataElement", System::String, bool>(a1) }
    fn is_closed_element(a1: System::String) -> bool { Self::static1::<"IsClosedElement", System::String, bool>(a1) }
    fn is_empty_element(a1: System::String) -> bool { Self::static1::<"IsEmptyElement", System::String, bool>(a1) }
    fn is_overlapped_closing_element(a1: System::String) -> bool { Self::static1::<"IsOverlappedClosingElement", System::String, bool>(a1) }
    fn append_child(self, a1: HtmlAgilityPack::HtmlNode) -> HtmlAgilityPack::HtmlNode { self.instance1::<"AppendChild", HtmlAgilityPack::HtmlNode, HtmlAgilityPack::HtmlNode>(a1) }
    fn set_child_nodes_id(self, a1: HtmlAgilityPack::HtmlNode) { self.instance1::<"SetChildNodesId", HtmlAgilityPack::HtmlNode, ()>(a1) }
    fn append_children(self, a1: HtmlAgilityPack::HtmlNodeCollection) { self.instance1::<"AppendChildren", HtmlAgilityPack::HtmlNodeCollection, ()>(a1) }
    fn clone(self) -> HtmlAgilityPack::HtmlNode { self.instance0::<"Clone", HtmlAgilityPack::HtmlNode>() }
    fn clone_node(self, a1: System::String) -> HtmlAgilityPack::HtmlNode { self.instance1::<"CloneNode", System::String, HtmlAgilityPack::HtmlNode>(a1) }
    fn copy_from(self, a1: HtmlAgilityPack::HtmlNode) { self.instance1::<"CopyFrom", HtmlAgilityPack::HtmlNode, ()>(a1) }
    fn element(self, a1: System::String) -> HtmlAgilityPack::HtmlNode { self.instance1::<"Element", System::String, HtmlAgilityPack::HtmlNode>(a1) }
    fn get_data_attribute(self, a1: System::String) -> HtmlAgilityPack::HtmlAttribute { self.instance1::<"GetDataAttribute", System::String, HtmlAgilityPack::HtmlAttribute>(a1) }
    fn get_attribute_value(self, a1: System::String, a2: System::String) -> System::String { self.instance2::<"GetAttributeValue", System::String, System::String, System::String>(a1, a2) }
    fn insert_after(self, a1: HtmlAgilityPack::HtmlNode, a2: HtmlAgilityPack::HtmlNode) -> HtmlAgilityPack::HtmlNode { self.instance2::<"InsertAfter", HtmlAgilityPack::HtmlNode, HtmlAgilityPack::HtmlNode, HtmlAgilityPack::HtmlNode>(a1, a2) }
    fn insert_before(self, a1: HtmlAgilityPack::HtmlNode, a2: HtmlAgilityPack::HtmlNode) -> HtmlAgilityPack::HtmlNode { self.instance2::<"InsertBefore", HtmlAgilityPack::HtmlNode, HtmlAgilityPack::HtmlNode, HtmlAgilityPack::HtmlNode>(a1, a2) }
    fn prepend_child(self, a1: HtmlAgilityPack::HtmlNode) -> HtmlAgilityPack::HtmlNode { self.instance1::<"PrependChild", HtmlAgilityPack::HtmlNode, HtmlAgilityPack::HtmlNode>(a1) }
    fn prepend_children(self, a1: HtmlAgilityPack::HtmlNodeCollection) { self.instance1::<"PrependChildren", HtmlAgilityPack::HtmlNodeCollection, ()>(a1) }
    fn remove(self) { self.instance0::<"Remove", ()>() }
    fn remove_all(self) { self.instance0::<"RemoveAll", ()>() }
    fn remove_all_children(self) { self.instance0::<"RemoveAllChildren", ()>() }
    fn remove_all_idfor_node(self, a1: HtmlAgilityPack::HtmlNode) { self.instance1::<"RemoveAllIDforNode", HtmlAgilityPack::HtmlNode, ()>(a1) }
    fn move_child(self, a1: HtmlAgilityPack::HtmlNode) { self.instance1::<"MoveChild", HtmlAgilityPack::HtmlNode, ()>(a1) }
    fn move_children(self, a1: HtmlAgilityPack::HtmlNodeCollection) { self.instance1::<"MoveChildren", HtmlAgilityPack::HtmlNodeCollection, ()>(a1) }
    fn remove_children(self, a1: HtmlAgilityPack::HtmlNodeCollection) { self.instance1::<"RemoveChildren", HtmlAgilityPack::HtmlNodeCollection, ()>(a1) }
    fn remove_child(self, a1: HtmlAgilityPack::HtmlNode) -> HtmlAgilityPack::HtmlNode { self.instance1::<"RemoveChild", HtmlAgilityPack::HtmlNode, HtmlAgilityPack::HtmlNode>(a1) }
    fn replace_child(self, a1: HtmlAgilityPack::HtmlNode, a2: HtmlAgilityPack::HtmlNode) -> HtmlAgilityPack::HtmlNode { self.instance2::<"ReplaceChild", HtmlAgilityPack::HtmlNode, HtmlAgilityPack::HtmlNode, HtmlAgilityPack::HtmlNode>(a1, a2) }
    fn set_attribute_value(self, a1: System::String, a2: System::String) -> HtmlAgilityPack::HtmlAttribute { self.instance2::<"SetAttributeValue", System::String, System::String, HtmlAgilityPack::HtmlAttribute>(a1, a2) }
    fn write_content_to(self, a1: System::IO::TextWriter, a2: i32) { self.instance2::<"WriteContentTo", System::IO::TextWriter, i32, ()>(a1, a2) }
    fn write_to(self, a1: System::IO::TextWriter, a2: i32) { self.instance2::<"WriteTo", System::IO::TextWriter, i32, ()>(a1, a2) }
    fn set_parent(self, a1: HtmlAgilityPack::HtmlNode) { self.instance1::<"SetParent", HtmlAgilityPack::HtmlNode, ()>(a1) }
    fn add_class(self, a1: System::String) { self.instance1::<"AddClass", System::String, ()>(a1) }
    fn remove_class(self) { self.instance0::<"RemoveClass", ()>() }
    fn replace_class(self, a1: System::String, a2: System::String) { self.instance2::<"ReplaceClass", System::String, System::String, ()>(a1, a2) }
    fn has_class(self, a1: System::String) -> bool { self.instance1::<"HasClass", System::String, bool>(a1) }
    fn get_encapsulated_data(self, a1: System::Type, a2: HtmlAgilityPack::HtmlDocument) -> System::Object { self.instance2::<"GetEncapsulatedData", System::Type, HtmlAgilityPack::HtmlDocument, System::Object>(a1, a2) }
    fn select_nodes(self, a1: System::String) -> HtmlAgilityPack::HtmlNodeCollection { self.instance1::<"SelectNodes", System::String, HtmlAgilityPack::HtmlNodeCollection>(a1) }
    fn select_single_node(self, a1: System::String) -> HtmlAgilityPack::HtmlNode { self.instance1::<"SelectSingleNode", System::String, HtmlAgilityPack::HtmlNode>(a1) }
}
pub type HasXPathAttribute =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.HasXPathAttribute">;
use super::*;
impl UpcastTo<System::Attribute> for HasXPathAttribute {
 fn upcast(self)->System::Attribute{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::Attribute,HasXPathAttribute>(self)
}} 
pub trait HasXPathAttribute_Methods {
    fn new() -> Self;
}
impl HasXPathAttribute_Methods for HasXPathAttribute {
    fn new() -> Self { Self::ctor0() }
}
pub type XPathAttribute =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.XPathAttribute">;
use super::*;
impl UpcastTo<System::Attribute> for XPathAttribute {
 fn upcast(self)->System::Attribute{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::Attribute,XPathAttribute>(self)
}} 
pub trait XPathAttribute_Methods {
    fn get_xpath(self) -> System::String;
    fn get_attribute_name(self) -> System::String;
    fn set_attribute_name(self, a1: System::String);
    fn new(a1: System::String) -> Self;
}
impl XPathAttribute_Methods for XPathAttribute {
    fn get_xpath(self) -> System::String { self.instance0::<"get_XPath", System::String>() }
    fn get_attribute_name(self) -> System::String { self.instance0::<"get_AttributeName", System::String>() }
    fn set_attribute_name(self, a1: System::String) { self.instance1::<"set_AttributeName", System::String, ()>(a1) }
    fn new(a1: System::String) -> Self { Self::ctor1(a1) }
}
pub type SkipNodeNotFoundAttribute =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.SkipNodeNotFoundAttribute">;
use super::*;
impl UpcastTo<System::Attribute> for SkipNodeNotFoundAttribute {
 fn upcast(self)->System::Attribute{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::Attribute,SkipNodeNotFoundAttribute>(self)
}} 
pub trait SkipNodeNotFoundAttribute_Methods {
    fn new() -> Self;
}
impl SkipNodeNotFoundAttribute_Methods for SkipNodeNotFoundAttribute {
    fn new() -> Self { Self::ctor0() }
}
pub type NodeNotFoundException =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.NodeNotFoundException">;
use super::*;
impl UpcastTo<System::Exception> for NodeNotFoundException {
 fn upcast(self)->System::Exception{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::Exception,NodeNotFoundException>(self)
}} 
pub trait NodeNotFoundException_Methods {
    fn new() -> Self;
}
impl NodeNotFoundException_Methods for NodeNotFoundException {
    fn new() -> Self { Self::ctor0() }
}
pub type NodeAttributeNotFoundException =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.NodeAttributeNotFoundException">;
use super::*;
impl UpcastTo<System::Exception> for NodeAttributeNotFoundException {
 fn upcast(self)->System::Exception{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::Exception,NodeAttributeNotFoundException>(self)
}} 
pub trait NodeAttributeNotFoundException_Methods {
    fn new() -> Self;
}
impl NodeAttributeNotFoundException_Methods for NodeAttributeNotFoundException {
    fn new() -> Self { Self::ctor0() }
}
pub type MissingXPathException =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.MissingXPathException">;
use super::*;
impl UpcastTo<System::Exception> for MissingXPathException {
 fn upcast(self)->System::Exception{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::Exception,MissingXPathException>(self)
}} 
pub trait MissingXPathException_Methods {
    fn new() -> Self;
}
impl MissingXPathException_Methods for MissingXPathException {
    fn new() -> Self { Self::ctor0() }
}
pub type InvalidNodeReturnTypeException =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.InvalidNodeReturnTypeException">;
use super::*;
impl UpcastTo<System::Exception> for InvalidNodeReturnTypeException {
 fn upcast(self)->System::Exception{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::Exception,InvalidNodeReturnTypeException>(self)
}} 
pub trait InvalidNodeReturnTypeException_Methods {
    fn new(a1: System::String) -> Self;
}
impl InvalidNodeReturnTypeException_Methods for InvalidNodeReturnTypeException {
    fn new(a1: System::String) -> Self { Self::ctor1(a1) }
}
pub type HtmlNodeCollection =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.HtmlNodeCollection">;
use super::*;
impl UpcastTo<System::Object> for HtmlNodeCollection {
 fn upcast(self)->System::Object{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::Object,HtmlNodeCollection>(self)
}} 
pub trait HtmlNodeCollection_Methods {
    fn get_item(self, a1: HtmlAgilityPack::HtmlNode) -> i32;
    fn get_count(self) -> i32;
    fn get_is_read_only(self) -> bool;
    fn set_item(self, a1: i32, a2: HtmlAgilityPack::HtmlNode);
    fn add(self, a1: HtmlAgilityPack::HtmlNode);
    fn clear(self);
    fn contains(self, a1: HtmlAgilityPack::HtmlNode) -> bool;
    fn index_of(self, a1: HtmlAgilityPack::HtmlNode) -> i32;
    fn insert(self, a1: i32, a2: HtmlAgilityPack::HtmlNode);
    fn remove(self, a1: HtmlAgilityPack::HtmlNode) -> bool;
    fn remove_at(self, a1: i32);
    fn find_first(a1: HtmlAgilityPack::HtmlNodeCollection, a2: System::String) -> HtmlAgilityPack::HtmlNode;
    fn append(self, a1: HtmlAgilityPack::HtmlNode);
    fn get_node_index(self, a1: HtmlAgilityPack::HtmlNode) -> i32;
    fn prepend(self, a1: HtmlAgilityPack::HtmlNode);
    fn replace(self, a1: i32, a2: HtmlAgilityPack::HtmlNode);
    fn new(a1: HtmlAgilityPack::HtmlNode) -> Self;
}
impl HtmlNodeCollection_Methods for HtmlNodeCollection {
    fn get_item(self, a1: HtmlAgilityPack::HtmlNode) -> i32 { self.instance1::<"get_Item", HtmlAgilityPack::HtmlNode, i32>(a1) }
    fn get_count(self) -> i32 { self.virt0::<"get_Count", i32>() }
    fn get_is_read_only(self) -> bool { self.virt0::<"get_IsReadOnly", bool>() }
    fn set_item(self, a1: i32, a2: HtmlAgilityPack::HtmlNode) { self.instance2::<"set_Item", i32, HtmlAgilityPack::HtmlNode, ()>(a1, a2) }
    fn add(self, a1: HtmlAgilityPack::HtmlNode) { self.instance1::<"Add", HtmlAgilityPack::HtmlNode, ()>(a1) }
    fn clear(self) { self.virt0::<"Clear", ()>() }
    fn contains(self, a1: HtmlAgilityPack::HtmlNode) -> bool { self.instance1::<"Contains", HtmlAgilityPack::HtmlNode, bool>(a1) }
    fn index_of(self, a1: HtmlAgilityPack::HtmlNode) -> i32 { self.instance1::<"IndexOf", HtmlAgilityPack::HtmlNode, i32>(a1) }
    fn insert(self, a1: i32, a2: HtmlAgilityPack::HtmlNode) { self.instance2::<"Insert", i32, HtmlAgilityPack::HtmlNode, ()>(a1, a2) }
    fn remove(self, a1: HtmlAgilityPack::HtmlNode) -> bool { self.instance1::<"Remove", HtmlAgilityPack::HtmlNode, bool>(a1) }
    fn remove_at(self, a1: i32) { self.instance1::<"RemoveAt", i32, ()>(a1) }
    fn find_first(a1: HtmlAgilityPack::HtmlNodeCollection, a2: System::String) -> HtmlAgilityPack::HtmlNode { Self::static2::<"FindFirst", HtmlAgilityPack::HtmlNodeCollection, System::String, HtmlAgilityPack::HtmlNode>(a1, a2) }
    fn append(self, a1: HtmlAgilityPack::HtmlNode) { self.instance1::<"Append", HtmlAgilityPack::HtmlNode, ()>(a1) }
    fn get_node_index(self, a1: HtmlAgilityPack::HtmlNode) -> i32 { self.instance1::<"GetNodeIndex", HtmlAgilityPack::HtmlNode, i32>(a1) }
    fn prepend(self, a1: HtmlAgilityPack::HtmlNode) { self.instance1::<"Prepend", HtmlAgilityPack::HtmlNode, ()>(a1) }
    fn replace(self, a1: i32, a2: HtmlAgilityPack::HtmlNode) { self.instance2::<"Replace", i32, HtmlAgilityPack::HtmlNode, ()>(a1, a2) }
    fn new(a1: HtmlAgilityPack::HtmlNode) -> Self { Self::ctor1(a1) }
}
pub type HtmlNodeNavigator =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.HtmlNodeNavigator">;
use super::*;
pub trait HtmlNodeNavigator_Methods {
    fn get_base_uri(self) -> System::String;
    fn get_current_document(self) -> HtmlAgilityPack::HtmlDocument;
    fn get_current_node(self) -> HtmlAgilityPack::HtmlNode;
    fn get_has_attributes(self) -> bool;
    fn get_has_children(self) -> bool;
    fn get_is_empty_element(self) -> bool;
    fn get_local_name(self) -> System::String;
    fn get_name(self) -> System::String;
    fn get_namespace_uri(self) -> System::String;
    fn get_prefix(self) -> System::String;
    fn get_value(self) -> System::String;
    fn get_xml_lang(self) -> System::String;
    fn get_attribute(self, a1: System::String, a2: System::String) -> System::String;
    fn get_namespace(self, a1: System::String) -> System::String;
    fn move_to_attribute(self, a1: System::String, a2: System::String) -> bool;
    fn move_to_first(self) -> bool;
    fn move_to_first_attribute(self) -> bool;
    fn move_to_first_child(self) -> bool;
    fn move_to_id(self, a1: System::String) -> bool;
    fn move_to_namespace(self, a1: System::String) -> bool;
    fn move_to_next(self) -> bool;
    fn move_to_next_attribute(self) -> bool;
    fn move_to_parent(self) -> bool;
    fn move_to_previous(self) -> bool;
    fn move_to_root(self);
    fn new(a1: System::IO::Stream) -> Self;
}
impl HtmlNodeNavigator_Methods for HtmlNodeNavigator {
    fn get_base_uri(self) -> System::String { self.virt0::<"get_BaseURI", System::String>() }
    fn get_current_document(self) -> HtmlAgilityPack::HtmlDocument { self.instance0::<"get_CurrentDocument", HtmlAgilityPack::HtmlDocument>() }
    fn get_current_node(self) -> HtmlAgilityPack::HtmlNode { self.instance0::<"get_CurrentNode", HtmlAgilityPack::HtmlNode>() }
    fn get_has_attributes(self) -> bool { self.virt0::<"get_HasAttributes", bool>() }
    fn get_has_children(self) -> bool { self.virt0::<"get_HasChildren", bool>() }
    fn get_is_empty_element(self) -> bool { self.virt0::<"get_IsEmptyElement", bool>() }
    fn get_local_name(self) -> System::String { self.virt0::<"get_LocalName", System::String>() }
    fn get_name(self) -> System::String { self.virt0::<"get_Name", System::String>() }
    fn get_namespace_uri(self) -> System::String { self.virt0::<"get_NamespaceURI", System::String>() }
    fn get_prefix(self) -> System::String { self.virt0::<"get_Prefix", System::String>() }
    fn get_value(self) -> System::String { self.virt0::<"get_Value", System::String>() }
    fn get_xml_lang(self) -> System::String { self.virt0::<"get_XmlLang", System::String>() }
    fn get_attribute(self, a1: System::String, a2: System::String) -> System::String { self.instance2::<"GetAttribute", System::String, System::String, System::String>(a1, a2) }
    fn get_namespace(self, a1: System::String) -> System::String { self.instance1::<"GetNamespace", System::String, System::String>(a1) }
    fn move_to_attribute(self, a1: System::String, a2: System::String) -> bool { self.instance2::<"MoveToAttribute", System::String, System::String, bool>(a1, a2) }
    fn move_to_first(self) -> bool { self.virt0::<"MoveToFirst", bool>() }
    fn move_to_first_attribute(self) -> bool { self.virt0::<"MoveToFirstAttribute", bool>() }
    fn move_to_first_child(self) -> bool { self.virt0::<"MoveToFirstChild", bool>() }
    fn move_to_id(self, a1: System::String) -> bool { self.instance1::<"MoveToId", System::String, bool>(a1) }
    fn move_to_namespace(self, a1: System::String) -> bool { self.instance1::<"MoveToNamespace", System::String, bool>(a1) }
    fn move_to_next(self) -> bool { self.virt0::<"MoveToNext", bool>() }
    fn move_to_next_attribute(self) -> bool { self.virt0::<"MoveToNextAttribute", bool>() }
    fn move_to_parent(self) -> bool { self.virt0::<"MoveToParent", bool>() }
    fn move_to_previous(self) -> bool { self.virt0::<"MoveToPrevious", bool>() }
    fn move_to_root(self) { self.virt0::<"MoveToRoot", ()>() }
    fn new(a1: System::IO::Stream) -> Self { Self::ctor1(a1) }
}
pub type HtmlParseError =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.HtmlParseError">;
use super::*;
impl UpcastTo<System::Object> for HtmlParseError {
 fn upcast(self)->System::Object{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::Object,HtmlParseError>(self)
}} 
pub trait HtmlParseError_Methods {
    fn get_line(self) -> i32;
    fn get_line_position(self) -> i32;
    fn get_reason(self) -> System::String;
    fn get_source_text(self) -> System::String;
    fn get_stream_position(self) -> i32;
}
impl HtmlParseError_Methods for HtmlParseError {
    fn get_line(self) -> i32 { self.instance0::<"get_Line", i32>() }
    fn get_line_position(self) -> i32 { self.instance0::<"get_LinePosition", i32>() }
    fn get_reason(self) -> System::String { self.instance0::<"get_Reason", System::String>() }
    fn get_source_text(self) -> System::String { self.instance0::<"get_SourceText", System::String>() }
    fn get_stream_position(self) -> i32 { self.instance0::<"get_StreamPosition", i32>() }
}
pub type HtmlTextNode =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.HtmlTextNode">;
use super::*;
impl UpcastTo<HtmlAgilityPack::HtmlNode> for HtmlTextNode {
 fn upcast(self)->HtmlAgilityPack::HtmlNode{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<HtmlAgilityPack::HtmlNode,HtmlTextNode>(self)
}} 
pub trait HtmlTextNode_Methods {
    fn get_inner_html(self) -> System::String;
    fn set_inner_html(self, a1: System::String);
    fn get_outer_html(self) -> System::String;
    fn get_text(self) -> System::String;
    fn set_text(self, a1: System::String);
}
impl HtmlTextNode_Methods for HtmlTextNode {
    fn get_inner_html(self) -> System::String { self.virt0::<"get_InnerHtml", System::String>() }
    fn set_inner_html(self, a1: System::String) { self.instance1::<"set_InnerHtml", System::String, ()>(a1) }
    fn get_outer_html(self) -> System::String { self.virt0::<"get_OuterHtml", System::String>() }
    fn get_text(self) -> System::String { self.instance0::<"get_Text", System::String>() }
    fn set_text(self, a1: System::String) { self.instance1::<"set_Text", System::String, ()>(a1) }
}
pub type HtmlWeb =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.HtmlWeb">;
use super::*;
impl UpcastTo<System::Object> for HtmlWeb {
 fn upcast(self)->System::Object{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::Object,HtmlWeb>(self)
}} 
pub trait HtmlWeb_Methods {
    fn get_timeout(self) -> i32;
    fn set_timeout(self, a1: i32);
    fn get_auto_detect_encoding(self) -> bool;
    fn set_auto_detect_encoding(self, a1: bool);
    fn get_override_encoding(self) -> System::Text::Encoding;
    fn set_override_encoding(self, a1: System::Text::Encoding);
    fn get_cache_only(self) -> bool;
    fn set_cache_only(self, a1: bool);
    fn get_using_cache_if_exists(self) -> bool;
    fn set_using_cache_if_exists(self, a1: bool);
    fn get_cache_path(self) -> System::String;
    fn set_cache_path(self, a1: System::String);
    fn get_from_cache(self) -> bool;
    fn get_request_duration(self) -> i32;
    fn get_response_uri(self) -> System::Uri;
    fn get_stream_buffer_size(self) -> i32;
    fn set_stream_buffer_size(self, a1: i32);
    fn get_use_cookies(self) -> bool;
    fn set_use_cookies(self, a1: bool);
    fn get_capture_redirect(self) -> bool;
    fn set_capture_redirect(self, a1: bool);
    fn get_user_agent(self) -> System::String;
    fn set_user_agent(self, a1: System::String);
    fn get_using_cache(self) -> bool;
    fn set_using_cache(self, a1: bool);
    fn get_content_type_for_extension(a1: System::String, a2: System::String) -> System::String;
    fn get_extension_for_content_type(a1: System::String, a2: System::String) -> System::String;
    fn create_instance(self, a1: System::String, a2: System::Type) -> System::Object;
    fn get(self, a1: System::String, a2: System::String);
    fn load(self, a1: System::String) -> HtmlAgilityPack::HtmlDocument;
    fn new() -> Self;
}
impl HtmlWeb_Methods for HtmlWeb {
    fn get_timeout(self) -> i32 { self.instance0::<"get_Timeout", i32>() }
    fn set_timeout(self, a1: i32) { self.instance1::<"set_Timeout", i32, ()>(a1) }
    fn get_auto_detect_encoding(self) -> bool { self.instance0::<"get_AutoDetectEncoding", bool>() }
    fn set_auto_detect_encoding(self, a1: bool) { self.instance1::<"set_AutoDetectEncoding", bool, ()>(a1) }
    fn get_override_encoding(self) -> System::Text::Encoding { self.instance0::<"get_OverrideEncoding", System::Text::Encoding>() }
    fn set_override_encoding(self, a1: System::Text::Encoding) { self.instance1::<"set_OverrideEncoding", System::Text::Encoding, ()>(a1) }
    fn get_cache_only(self) -> bool { self.instance0::<"get_CacheOnly", bool>() }
    fn set_cache_only(self, a1: bool) { self.instance1::<"set_CacheOnly", bool, ()>(a1) }
    fn get_using_cache_if_exists(self) -> bool { self.instance0::<"get_UsingCacheIfExists", bool>() }
    fn set_using_cache_if_exists(self, a1: bool) { self.instance1::<"set_UsingCacheIfExists", bool, ()>(a1) }
    fn get_cache_path(self) -> System::String { self.instance0::<"get_CachePath", System::String>() }
    fn set_cache_path(self, a1: System::String) { self.instance1::<"set_CachePath", System::String, ()>(a1) }
    fn get_from_cache(self) -> bool { self.instance0::<"get_FromCache", bool>() }
    fn get_request_duration(self) -> i32 { self.instance0::<"get_RequestDuration", i32>() }
    fn get_response_uri(self) -> System::Uri { self.instance0::<"get_ResponseUri", System::Uri>() }
    fn get_stream_buffer_size(self) -> i32 { self.instance0::<"get_StreamBufferSize", i32>() }
    fn set_stream_buffer_size(self, a1: i32) { self.instance1::<"set_StreamBufferSize", i32, ()>(a1) }
    fn get_use_cookies(self) -> bool { self.instance0::<"get_UseCookies", bool>() }
    fn set_use_cookies(self, a1: bool) { self.instance1::<"set_UseCookies", bool, ()>(a1) }
    fn get_capture_redirect(self) -> bool { self.instance0::<"get_CaptureRedirect", bool>() }
    fn set_capture_redirect(self, a1: bool) { self.instance1::<"set_CaptureRedirect", bool, ()>(a1) }
    fn get_user_agent(self) -> System::String { self.instance0::<"get_UserAgent", System::String>() }
    fn set_user_agent(self, a1: System::String) { self.instance1::<"set_UserAgent", System::String, ()>(a1) }
    fn get_using_cache(self) -> bool { self.instance0::<"get_UsingCache", bool>() }
    fn set_using_cache(self, a1: bool) { self.instance1::<"set_UsingCache", bool, ()>(a1) }
    fn get_content_type_for_extension(a1: System::String, a2: System::String) -> System::String { Self::static2::<"GetContentTypeForExtension", System::String, System::String, System::String>(a1, a2) }
    fn get_extension_for_content_type(a1: System::String, a2: System::String) -> System::String { Self::static2::<"GetExtensionForContentType", System::String, System::String, System::String>(a1, a2) }
    fn create_instance(self, a1: System::String, a2: System::Type) -> System::Object { self.instance2::<"CreateInstance", System::String, System::Type, System::Object>(a1, a2) }
    fn get(self, a1: System::String, a2: System::String) { self.instance2::<"Get", System::String, System::String, ()>(a1, a2) }
    fn load(self, a1: System::String) -> HtmlAgilityPack::HtmlDocument { self.instance1::<"Load", System::String, HtmlAgilityPack::HtmlDocument>(a1) }
    fn new() -> Self { Self::ctor0() }
}
pub type HtmlWebException =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.HtmlWebException">;
use super::*;
impl UpcastTo<System::Exception> for HtmlWebException {
 fn upcast(self)->System::Exception{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::Exception,HtmlWebException>(self)
}} 
pub trait HtmlWebException_Methods {
    fn new(a1: System::String) -> Self;
}
impl HtmlWebException_Methods for HtmlWebException {
    fn new(a1: System::String) -> Self { Self::ctor1(a1) }
}
pub type MixedCodeDocument =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.MixedCodeDocument">;
use super::*;
impl UpcastTo<System::Object> for MixedCodeDocument {
 fn upcast(self)->System::Object{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::Object,MixedCodeDocument>(self)
}} 
pub trait MixedCodeDocument_Methods {
    fn get_code(self) -> System::String;
    fn get_code_fragments(self) -> HtmlAgilityPack::MixedCodeDocumentFragmentList;
    fn get_fragments(self) -> HtmlAgilityPack::MixedCodeDocumentFragmentList;
    fn get_stream_encoding(self) -> System::Text::Encoding;
    fn get_text_fragments(self) -> HtmlAgilityPack::MixedCodeDocumentFragmentList;
    fn create_code_fragment(self) -> HtmlAgilityPack::MixedCodeDocumentCodeFragment;
    fn create_text_fragment(self) -> HtmlAgilityPack::MixedCodeDocumentTextFragment;
    fn load(self, a1: System::IO::Stream);
    fn load_html(self, a1: System::String);
    fn save(self, a1: System::IO::Stream);
    fn new() -> Self;
}
impl MixedCodeDocument_Methods for MixedCodeDocument {
    fn get_code(self) -> System::String { self.instance0::<"get_Code", System::String>() }
    fn get_code_fragments(self) -> HtmlAgilityPack::MixedCodeDocumentFragmentList { self.instance0::<"get_CodeFragments", HtmlAgilityPack::MixedCodeDocumentFragmentList>() }
    fn get_fragments(self) -> HtmlAgilityPack::MixedCodeDocumentFragmentList { self.instance0::<"get_Fragments", HtmlAgilityPack::MixedCodeDocumentFragmentList>() }
    fn get_stream_encoding(self) -> System::Text::Encoding { self.instance0::<"get_StreamEncoding", System::Text::Encoding>() }
    fn get_text_fragments(self) -> HtmlAgilityPack::MixedCodeDocumentFragmentList { self.instance0::<"get_TextFragments", HtmlAgilityPack::MixedCodeDocumentFragmentList>() }
    fn create_code_fragment(self) -> HtmlAgilityPack::MixedCodeDocumentCodeFragment { self.instance0::<"CreateCodeFragment", HtmlAgilityPack::MixedCodeDocumentCodeFragment>() }
    fn create_text_fragment(self) -> HtmlAgilityPack::MixedCodeDocumentTextFragment { self.instance0::<"CreateTextFragment", HtmlAgilityPack::MixedCodeDocumentTextFragment>() }
    fn load(self, a1: System::IO::Stream) { self.instance1::<"Load", System::IO::Stream, ()>(a1) }
    fn load_html(self, a1: System::String) { self.instance1::<"LoadHtml", System::String, ()>(a1) }
    fn save(self, a1: System::IO::Stream) { self.instance1::<"Save", System::IO::Stream, ()>(a1) }
    fn new() -> Self { Self::ctor0() }
}
pub type MixedCodeDocumentCodeFragment =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.MixedCodeDocumentCodeFragment">;
use super::*;
impl UpcastTo<HtmlAgilityPack::MixedCodeDocumentFragment> for MixedCodeDocumentCodeFragment {
 fn upcast(self)->HtmlAgilityPack::MixedCodeDocumentFragment{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<HtmlAgilityPack::MixedCodeDocumentFragment,MixedCodeDocumentCodeFragment>(self)
}} 
pub trait MixedCodeDocumentCodeFragment_Methods {
    fn get_code(self) -> System::String;
    fn set_code(self, a1: System::String);
}
impl MixedCodeDocumentCodeFragment_Methods for MixedCodeDocumentCodeFragment {
    fn get_code(self) -> System::String { self.instance0::<"get_Code", System::String>() }
    fn set_code(self, a1: System::String) { self.instance1::<"set_Code", System::String, ()>(a1) }
}
pub type MixedCodeDocumentFragment =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.MixedCodeDocumentFragment">;
use super::*;
impl UpcastTo<System::Object> for MixedCodeDocumentFragment {
 fn upcast(self)->System::Object{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::Object,MixedCodeDocumentFragment>(self)
}} 
pub trait MixedCodeDocumentFragment_Methods {
    fn get_fragment_text(self) -> System::String;
    fn get_line(self) -> i32;
    fn get_line_position(self) -> i32;
    fn get_stream_position(self) -> i32;
}
impl MixedCodeDocumentFragment_Methods for MixedCodeDocumentFragment {
    fn get_fragment_text(self) -> System::String { self.instance0::<"get_FragmentText", System::String>() }
    fn get_line(self) -> i32 { self.instance0::<"get_Line", i32>() }
    fn get_line_position(self) -> i32 { self.instance0::<"get_LinePosition", i32>() }
    fn get_stream_position(self) -> i32 { self.instance0::<"get_StreamPosition", i32>() }
}
pub type MixedCodeDocumentFragmentList =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.MixedCodeDocumentFragmentList">;
use super::*;
impl UpcastTo<System::Object> for MixedCodeDocumentFragmentList {
 fn upcast(self)->System::Object{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<System::Object,MixedCodeDocumentFragmentList>(self)
}} 
pub trait MixedCodeDocumentFragmentList_Methods {
    fn get_doc(self) -> HtmlAgilityPack::MixedCodeDocument;
    fn get_count(self) -> i32;
    fn get_item(self, a1: i32) -> HtmlAgilityPack::MixedCodeDocumentFragment;
    fn append(self, a1: HtmlAgilityPack::MixedCodeDocumentFragment);
    fn prepend(self, a1: HtmlAgilityPack::MixedCodeDocumentFragment);
    fn remove(self, a1: HtmlAgilityPack::MixedCodeDocumentFragment);
    fn remove_all(self);
    fn remove_at(self, a1: i32);
}
impl MixedCodeDocumentFragmentList_Methods for MixedCodeDocumentFragmentList {
    fn get_doc(self) -> HtmlAgilityPack::MixedCodeDocument { self.instance0::<"get_Doc", HtmlAgilityPack::MixedCodeDocument>() }
    fn get_count(self) -> i32 { self.instance0::<"get_Count", i32>() }
    fn get_item(self, a1: i32) -> HtmlAgilityPack::MixedCodeDocumentFragment { self.instance1::<"get_Item", i32, HtmlAgilityPack::MixedCodeDocumentFragment>(a1) }
    fn append(self, a1: HtmlAgilityPack::MixedCodeDocumentFragment) { self.instance1::<"Append", HtmlAgilityPack::MixedCodeDocumentFragment, ()>(a1) }
    fn prepend(self, a1: HtmlAgilityPack::MixedCodeDocumentFragment) { self.instance1::<"Prepend", HtmlAgilityPack::MixedCodeDocumentFragment, ()>(a1) }
    fn remove(self, a1: HtmlAgilityPack::MixedCodeDocumentFragment) { self.instance1::<"Remove", HtmlAgilityPack::MixedCodeDocumentFragment, ()>(a1) }
    fn remove_all(self) { self.instance0::<"RemoveAll", ()>() }
    fn remove_at(self, a1: i32) { self.instance1::<"RemoveAt", i32, ()>(a1) }
}
pub type MixedCodeDocumentTextFragment =  mycorrhiza::intrinsics::RustcCLRInteropManagedClass<"HtmlAgilityPack","HtmlAgilityPack.MixedCodeDocumentTextFragment">;
use super::*;
impl UpcastTo<HtmlAgilityPack::MixedCodeDocumentFragment> for MixedCodeDocumentTextFragment {
 fn upcast(self)->HtmlAgilityPack::MixedCodeDocumentFragment{
mycorrhiza::intrinsics::rustc_clr_interop_managed_checked_cast::<HtmlAgilityPack::MixedCodeDocumentFragment,MixedCodeDocumentTextFragment>(self)
}} 
pub trait MixedCodeDocumentTextFragment_Methods {
    fn get_text(self) -> System::String;
    fn set_text(self, a1: System::String);
}
impl MixedCodeDocumentTextFragment_Methods for MixedCodeDocumentTextFragment {
    fn get_text(self) -> System::String { self.instance0::<"get_Text", System::String>() }
    fn set_text(self, a1: System::String) { self.instance1::<"set_Text", System::String, ()>(a1) }
}
}
