//! C-header to Rust declaration generation for the `cargo dotnet` P/Invoke surface.
//!
//! This crate owns source generation only. Package acquisition stays in `rust-dotnet-assets`,
//! command-line policy stays in `cargo-dotnet`, and the compiler consumes the resulting ordinary
//! Rust `#[link] extern` declarations without knowing that they were generated.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

#[derive(Clone, Debug)]
pub struct BindgenConfig {
    pub header: PathBuf,
    pub library: String,
    pub output: PathBuf,
    pub allowlist_functions: Vec<String>,
    pub allowlist_types: Vec<String>,
    pub blocklist_items: Vec<String>,
    pub clang_args: Vec<String>,
    pub derive_default: bool,
    pub layout_tests: bool,
    /// Verify that the checked-in output is current without modifying it.
    pub check: bool,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GenerationReport {
    pub output: PathBuf,
    pub extern_blocks: usize,
    pub changed: bool,
}

pub fn generate(config: &BindgenConfig) -> Result<GenerationReport> {
    validate(config)?;
    let rust_target = bindgen::RustTarget::stable(82, 0)
        .expect("bindgen supports the Rust 1.82 target required for unsafe extern blocks");
    let mut builder = bindgen::Builder::default()
        .header(config.header.to_string_lossy())
        .clang_arg("-x")
        .clang_arg("c")
        .rust_target(rust_target)
        .rust_edition(bindgen::RustEdition::Edition2021)
        .derive_default(config.derive_default)
        .layout_tests(config.layout_tests)
        .generate_comments(true)
        .merge_extern_blocks(true)
        .sort_semantically(true);
    for pattern in &config.allowlist_functions {
        builder = builder.allowlist_function(pattern);
    }
    for pattern in &config.allowlist_types {
        builder = builder.allowlist_type(pattern);
    }
    for pattern in &config.blocklist_items {
        builder = builder.blocklist_item(pattern);
    }
    for argument in &config.clang_args {
        builder = builder.clang_arg(argument);
    }

    let bindings = builder.generate().map_err(|error| {
        anyhow::anyhow!(
            "bindgen could not parse {}; install libclang and pass include paths with --clang-arg: {error}",
            config.header.display(),
        )
    })?;
    let generated = bindings.to_string();
    let (linked, extern_blocks) = add_link_attributes(&generated, &config.library);
    if extern_blocks == 0 {
        bail!(
            "{} produced no C function declarations; check the allowlists and header include paths",
            config.header.display()
        );
    }
    let source = format!(
        "// @generated by `cargo dotnet bindgen`; edit the header or command, not this file.\n\
         #![allow(dead_code, non_camel_case_types, non_snake_case, non_upper_case_globals)]\n\n{linked}"
    );
    let changed = if config.check {
        if std::fs::read(&config.output).ok().as_deref() != Some(source.as_bytes()) {
            bail!(
                "generated bindings are stale: {}; rerun `cargo dotnet bindgen` without --check",
                config.output.display()
            );
        }
        false
    } else {
        write_if_changed(&config.output, source.as_bytes())?
    };
    Ok(GenerationReport {
        output: config.output.clone(),
        extern_blocks,
        changed,
    })
}

fn validate(config: &BindgenConfig) -> Result<()> {
    if !config.header.is_file() {
        bail!("C header does not exist: {}", config.header.display());
    }
    if config.library.trim().is_empty() {
        bail!("P/Invoke library name cannot be empty");
    }
    if config.library.contains('\0') {
        bail!("P/Invoke library name cannot contain NUL");
    }
    if config.output.extension().and_then(|ext| ext.to_str()) != Some("rs") {
        bail!("generated binding output must have a .rs extension");
    }
    Ok(())
}

fn add_link_attributes(source: &str, library: &str) -> (String, usize) {
    let attribute = format!("#[link(name = {:?})]", library);
    let mut output = String::with_capacity(source.len() + attribute.len());
    let mut count = 0;
    for line in source.split_inclusive('\n') {
        let item = line.trim_start();
        if item.starts_with("unsafe extern \"C\" {") || item.starts_with("extern \"C\" {") {
            let indent = &line[..line.len() - item.len()];
            output.push_str(indent);
            output.push_str(&attribute);
            output.push('\n');
            count += 1;
        }
        output.push_str(line);
    }
    (output, count)
}

fn write_if_changed(path: &Path, bytes: &[u8]) -> Result<bool> {
    if std::fs::read(path).ok().as_deref() == Some(bytes) {
        return Ok(false);
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    let temporary = path.with_extension("rs.tmp");
    std::fs::write(&temporary, bytes)
        .with_context(|| format!("writing {}", temporary.display()))?;
    if path.exists() {
        std::fs::remove_file(path).with_context(|| format!("replacing {}", path.display()))?;
    }
    std::fs::rename(&temporary, path)
        .with_context(|| format!("installing generated bindings at {}", path.display()))?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn link_attribute_is_attached_to_each_foreign_block() {
        let source = "pub struct Point { pub x: i32 }\nunsafe extern \"C\" {\n    pub fn sum(x: i32) -> i32;\n}\n";
        let (source, count) = add_link_attributes(source, "native-name");
        assert_eq!(count, 1);
        assert!(source.contains("#[link(name = \"native-name\")]\nunsafe extern \"C\""));
    }

    #[test]
    fn unchanged_output_is_not_rewritten() {
        let root = std::env::temp_dir().join(format!(
            "rust-dotnet-bindgen-{}-{}",
            std::process::id(),
            std::thread::current().name().unwrap_or("test")
        ));
        let path = root.join("bindings.rs");
        assert!(write_if_changed(&path, b"same").unwrap());
        assert!(!write_if_changed(&path, b"same").unwrap());
        std::fs::remove_dir_all(root).unwrap();
    }
}
