[package]
name = "rust-dotnet-sdk-core"
version = "0.0.2"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
serde = { version = "1.0.183", features = ["derive"] }
sha2 = "0.10"
tempfile = "3"

[target.'cfg(unix)'.dependencies]
rustix = { version = "1.1.4", features = ["fs"] }
